Initial commit
beaconFUN/mid-report2020 pull request #10
Opened 2020-09-17 12:44 UTC by Ryuku-Hisa

本文の内容と，誤字・脱字の確認をお願いします．

また，キーワードをどんな漢字にすればいいか，いまいちピンと来ていません．
いい代替案があれば教えてください．

2020-09-17 12:46 UTC, Ryuku-Hisa commented on abstract.tex
> +%英語の概要
英語のやつは，日本語が終わったらやります

2020-09-17 13:09 UTC, 212naoki approved these changes
気になったところにコメントしました

2020-09-17 13:32 UTC, Ryuku-Hisa commented on abstract.tex
> +このような魅力的な観光資源が多く存在しているによって、観光客が毎年多く訪れる。
```suggestion
このような魅力的な観光資源が多く存在していることによって、観光客が毎年多く訪れる。
```

2020-09-17 13:32 UTC, Ryuku-Hisa commented on abstract.tex
> +さらに、「函館らしさ」「ビーコンである理由」「必要性」「新規性」「不変的な魅力（継続性）」の観点から、複数のアイデアを創出し、9個のアイデアに絞り込んだ。
```suggestion
さらに、「函館らしさ」「ビーコンである理由」「必要性」「新規性」「不変的な魅力（継続性）」の観点から、複数のアイデアを創出して9個に絞り込んだ。
```

2020-09-17 13:33 UTC, Ryuku-Hisa commented on abstract.tex
> +%英語の概要
なおちた

2020-09-17 13:43 UTC, massu116 requested changes

2020-09-17 13:43 UTC, massu116 commented on abstract.tex
> +後期では、まず、これらのアイデアをさらにブラッシュアップし、3つまたは4つのアイデアに絞り込む。
```suggestion
後期では、これらのアイデアをさらにブラッシュアップし、3つまたは4つのアイデアに絞り込む。
```
その後〜っていう感じで文章が繋がっているから、まずっていらない気がする...

2020-09-17 13:47 UTC, massu116 approved these changes
見た感じOKですー

2020-09-17 13:52 UTC, 212naoki approved these changes
大丈夫そう！
お騒がせいたしましたm(_ _)m

2020-09-17 14:20 UTC, naonom commented on abstract.tex
> +さらに、「函館らしさ」「ビーコンである理由」「必要性」「新規性」「不変的な魅力（継続性）」の観点から、複数のアイデアを創出して9個に絞り込んだ。
```suggestion
さらに、「サービスの函館らしさ」「ビーコンである理由」「ビーコンである必要性」「ビーコンである新規性」「サービスの不変的な魅力（継続性）」の観点から、複数のアイデアを創出して9個に絞り込んだ。
```

2020-09-17 14:20 UTC, naonom commented on abstract.tex
> +さらに、「函館らしさ」「ビーコンである理由」「必要性」「新規性」「不変的な魅力（継続性）」の観点から、複数のアイデアを創出して9個に絞り込んだ。
3章では、1つ1つに主語をつけたから、つけた方が良いかも

2020-09-17 14:25 UTC, naonom commented on abstract.tex
> +さらに、「函館らしさ」「ビーコンである理由」「必要性」「新規性」「不変的な魅力（継続性）」の観点から、複数のアイデアを創出して9個に絞り込んだ。
「サービスの必要性」と「サービスの新規性」だめっちゃ事故してる

2020-09-18 05:38 UTC, 212naoki approved these changes

2020-09-18 09:16 UTC, massu116 approved these changes
OKだと思いますー

2020-09-18 09:19 UTC, TomSuzuki approved these changes

2020-09-18 11:11 UTC, merged