[feat] Chapter4の文章を追加
beaconFUN/mid-report2020 pull request #11
Opened 2020-09-17 12:46 UTC by mrs1669

# 概要
Chapter4の文を追加
![寿司ゆき:hello](https://d1zd1v0cxnbx2w.cloudfront.net/images/sets/sushiyuki/39.png)

2020-09-17 12:50 UTC, mrs1669 commented
VSCode用のTSモジュールが追跡対象に入ってしまっていたので外しました
![エンジニアを褒めるネコ:HelloWorld](https://raw.githubusercontent.com/fukayatsu/lttm-crx/master/vendor/%E3%82%A8%E3%83%B3%E3%82%B8%E3%83%8B%E3%82%A2%E3%82%92%E8%A4%92%E3%82%81%E3%82%8B%E3%83%8D%E3%82%B3/03_HelloWorld.png)

2020-09-17 12:52 UTC, kumakou reviewed
ピリオドとカンマを句読点にかえればOK

2020-09-17 12:53 UTC, mrs1669 commented
Chapter番号が残っていたので消去しました
![家系ラーメンのイラスト（うずらの卵）](https://3.bp.blogspot.com/-bm3--S5ghOk/V2ubxIX3ntI/AAAAAAAA7r0/RE9YYO3z3j8vv8-nC0wEEJ8to-A-KYbQwCLcB/s400/food_ramen_iekei_uzura.png)

2020-09-17 12:58 UTC, mrs1669 commented
コンマ、ピリオドを句点読点に修正しました。
文責はまだ決まってないので "hoge" になってます。
![ミサワ](https://livedoor.blogimg.jp/jigokuno_misawa/imgs/b/d/bdf681ff.gif)

2020-09-17 13:04 UTC, kume-negitoro requested changes
確認お願いします！

2020-09-17 13:04 UTC, kume-negitoro commented on chapter4.tex
> +    \item 発表動画がわかりやすくて，どのようなことを行ってきたかよく理解できた
ここは修正漏れですかね？
```suggestion
    \item 発表動画がわかりやすくて、どのようなことを行ってきたかよく理解できた
```

2020-09-17 13:11 UTC, mrs1669 commented on chapter4.tex
> +    \item 発表動画がわかりやすくて，どのようなことを行ってきたかよく理解できた
修正もれです！直します

2020-09-17 13:24 UTC, kume-negitoro requested changes
さっきの修正確認しました！
こちらも確認お願いします！

2020-09-17 13:24 UTC, kume-negitoro commented on chapter4.tex
> +などが得られ、聞き手にうまく伝えることができていた。以上から発表技術に問題はなかったと言える。低評価な意見としては、
「うまく」の部分と、言い切りの形がちょっと心配だったので指摘します。参考程度にお願いします。
```suggestion
などが得られた。以上から聞き手にわかりやすく伝えることができたと考えられるため、発表技術に問題はなかったと言える。低評価な意見としては、
```

2020-09-17 13:31 UTC, mrs1669 commented on chapter4.tex
> +などが得られ、聞き手にうまく伝えることができていた。以上から発表技術に問題はなかったと言える。低評価な意見としては、
こっちの方がいいですね！
![エンジニアを褒めるネコ:LGTM](https://raw.githubusercontent.com/fukayatsu/lttm-crx/master/vendor/%E3%82%A8%E3%83%B3%E3%82%B8%E3%83%8B%E3%82%A2%E3%82%92%E8%A4%92%E3%82%81%E3%82%8B%E3%83%8D%E3%82%B3/01_LGTM.png)

2020-09-17 13:33 UTC, mrs1669 commented
日本語修正しました！
![エンジニアを褒めるネコ:寝るまでが今日](https://raw.githubusercontent.com/fukayatsu/lttm-crx/master/vendor/%E3%82%A8%E3%83%B3%E3%82%B8%E3%83%8B%E3%82%A2%E3%82%92%E8%A4%92%E3%82%81%E3%82%8B%E3%83%8D%E3%82%B3/19_%E5%AF%9D%E3%82%8B%E3%81%BE%E3%81%A7%E3%81%8C%E4%BB%8A%E6%97%A5.png)

2020-09-17 14:31 UTC, ym223 commented on chapter4.tex
> +などが得られた。46件の回答が得られ、平均評価は10点中、7.8点であった。以上から、合成音声になじみが無い人にとっては聞き取りずらい動画発表であったことがわかった。
気になる(´・ω・｀)
```suggestion
などが得られた。46件の回答が得られ、平均評価は10点中、7.8点であった。以上から、合成音声になじみが無い人にとっては聞き取りづらい動画発表であったことがわかった。
```

2020-09-17 15:02 UTC, kume-negitoro submitted a review, later dismissed
LGTMです！

2020-09-17 16:05 UTC, kumakou submitted a review, later dismissed

2020-09-18 04:21 UTC, mrs1669 commented
@kume-negitoro @kumakou 
一部修正を加えたのでもう一度レビューしてもらえると助かります

修正点としては
- レビューでもらった意見について，カギカッコでくくった．
- 言える，行うなどの日本語をひらがなに変更．

みたいな感じです

2020-09-18 04:24 UTC, mrs1669 commented
一部懸念点があって，
もとのレビュー内容に手を加えていないため，12行目に「行ってきた」が漢字になっていたり，その他，レビューコメントは表記ゆれが多々あるのですが，この辺をそのままにしたほうがいいのか，それとも修正を加えてしまっていいのか，ちょっと意見もらえると助かります

2020-09-18 05:20 UTC, kumakou commented
> 一部懸念点があって，
> もとのレビュー内容に手を加えていないため，12行目に「行ってきた」が漢字になっていたり，その他，レビューコメントは表記ゆれが多々あるのですが，この辺をそのままにしたほうがいいのか，それとも修正を加えてしまっていいのか，ちょっと意見もらえると助かります

2020-09-18 05:23 UTC, kumakou commented
レビュー内容については加工しないでそのままでいいと思います。

2020-09-18 08:24 UTC, kumakou commented on chapter4.tex
> +　中間発表はオンラインでの開催であった。始めに、本プロジェクトの概要や仮アイデアの大まかな説明をおこなうため、10分間の動画とポスターを使用して発表した。その後、Zoomを使用して15分間の質疑応答を6回行った。
```suggestion
　中間発表はオンラインでの開催であった。始めに、本プロジェクトの概要や仮アイデアの大まかな説明をおこなうため、10分間の動画とポスターを使用して発表した。その後、Zoomを使用して15分間の質疑応答を6回おこなった。
```

2020-09-18 08:26 UTC, 212naoki commented on chapter4.tex
> +などが得られた。アンケートは46件の回答が得られ、平均評価は10点中、7.8点であった。以上から、合成音声になじみが無い人にとっては聞き取りずらい動画発表であったことがわかった。
```suggestion
などが得られた。アンケートは46件の回答が得られ、平均評価は10点中、7.8点であった。以上から、合成音声になじみが無い人にとっては聞き取りづらい動画発表であったことがわかった。
```

2020-09-18 08:30 UTC, kume-negitoro approved these changes
LGTM

2020-09-18 08:31 UTC, kumakou approved these changes

2020-09-18 08:34 UTC, merged