Initial commit
beaconFUN/mid-report2020 pull request #12
Opened 2020-09-17 13:04 UTC by naonom

３章の文章です
僕たちでは不足していたり憶測でしかかけていないところがあるので加筆して欲しいです。
「(・ω・｀)」がついてるところは憶測でも書けませんでした。

2020-09-17 14:03 UTC, ym223 commented on chapter3.tex
> +    \par このサービスは日本人・外国人問わず、様々な人とコミュニケーションをとることで、観光客が訪れやすい場所になり、観光客を増やすことができる。また、言語に対応した案内をすることで、観光客が快適に函館のまちを楽しむことができる。
ここは街…？どっち…？

2020-09-17 14:11 UTC, naonom commented on chapter3.tex
> +    \par このサービスは日本人・外国人問わず、様々な人とコミュニケーションをとることで、観光客が訪れやすい場所になり、観光客を増やすことができる。また、言語に対応した案内をすることで、観光客が快適に函館のまちを楽しむことができる。
街に修正しました。

2020-09-17 14:15 UTC, mrs1669 requested changes
![すき焼きのイラスト](https://1.bp.blogspot.com/-m42kXAuvYBo/UZ2U2fGHxbI/AAAAAAAAToU/NhzLPZ7vvTg/s400/food_sukiyaki.png)

2020-09-17 14:15 UTC, mrs1669 commented on chapter3.tex
> +    \par COVID-19が収束した後の函館を想定したサービス。環境客に函館の街を楽しんでもらうことや、幅広く函館の街を知ってもらうことがこのサービスの目的である。
コロナの名前統一問題

2020-09-17 14:15 UTC, mrs1669 commented on chapter3.tex
> +        \par 函館の景色を使ったサービスなので函館らしいと言える
語尾に句点あった方がいい

2020-09-17 14:15 UTC, mrs1669 commented on chapter3.tex
> +        \par 手軽に、深く函館について知る機会を提供することができる
語尾に句点ほしい

2020-09-17 14:15 UTC, mrs1669 commented on chapter3.tex
> +        \par 屋内のお店に訪れる際、屋内の位置情報はGPSでは取得することが難しいのでビーコンでサービスを実現する必要がある。また、ビーコンを用いることでどの店舗にどれくらい滞在したかなどの情報も取得することができるため、ビーコンでの実装をするべきである
語尾に句点欲しい

2020-09-17 14:15 UTC, mrs1669 commented on chapter3.tex
> +        \par 手軽に、深く函館について知る機会を提供することで、観光客が増え域内循環が向上される
語尾に句点欲しい

2020-09-17 14:15 UTC, mrs1669 commented on chapter3.tex
> +        \par 目的の図書がある場合は、図書位置がすぐに把握できるため、以前までのメモをとるという手間を省くことができる。分野の参考書などを借りたいなどの場合は、レビュー機能で図書の情報を得ることで、分野の中でもどれがおすすめなのかなど、借りたい図書を探す手助けができる。
図書、図書書いてあるけど、本の方がわかりやすそう

2020-09-17 14:57 UTC, ym223 commented on chapter3.tex
> +\subsection{俺を食ってくれ}
サービス名、こうらしいです！！(！は任意)
```suggestion
\subsection{俺を食ってくれぇ！}
```

2020-09-17 15:25 UTC, santyoume commented on chapter3.tex
> +        \par 複数のイベントが同じ場所で同時に行われていたとき、GPSでは本当に「目の前の」イベントかどうか判断することができない。また、イーコンを用いることでイベントの方から観光客や地元民にイベントについて働きかけることができる。これらの要因からこのサービスではビーコンを用いる必要がある。
イーコン　-> ビーコン
```suggestion
        \par 複数のイベントが同じ場所で同時に行われていたとき、GPSでは本当に「目の前の」イベントかどうか判断することができない。また、ビーコンを用いることでイベントの方から観光客や地元民にイベントについて働きかけることができる。これらの要因からこのサービスではビーコンを用いる必要がある。
```

2020-09-17 15:28 UTC, santyoume commented on chapter3.tex
> +        \par このサービスを提供することで、客に店の梯子を促すことがえきる。梯子を促すことで地域全体の活性化につながる。
梯子の漢字ってあまり馴染みがない気がした
```suggestion
        \par このサービスを提供することで、客に店のはしごを促すことがえきる。はしごを促すことで地域全体の活性化につながる。
```

2020-09-17 15:45 UTC, mrs1669 commented on chapter3.tex
> +    \par COVID-19が収束した後の函館を想定したサービス。環境客に函館の街を楽しんでもらうことや、幅広く函館の街を知ってもらうことがこのサービスの目的である。
covid-19に統一されたっぽい

2020-09-17 15:46 UTC, ym223 commented on chapter3.tex
> +    \par 函館は海に囲まれたであり、豊富な海産物に恵まれているという特徴がある。朝市やスーパーには、獲れたてのイカやホッケなど、新鮮な海産物が並ぶ。これらの海産物は飲食店だけでなく、地域住民や観光客からも多く求められている。
私だ〜ごめんん〜〜
```suggestion
    \par 函館は海に囲まれた街であり、豊富な海産物に恵まれているという特徴がある。朝市やスーパーには、獲れたてのイカやホッケなど、新鮮な海産物が並ぶ。これらの海産物は飲食店だけでなく、地域住民や観光客からも多く求められている。
```

2020-09-17 16:34 UTC, ym223 commented on chapter3.tex
> +    \par 函館の新鮮な海産物を買う際に、どの海産物の鮮度が鮮度が良いのか、どのように調理して良いのか分からない。しかし、店員に話しかけるのは難易度が高い場合もある。本サービスでは、このような課題を解決できると考える。
分かる->わかる
この章はここだけだったし、他のとこも平仮名表記っぽかった
```suggestion
    \par 函館の新鮮な海産物を買う際に、どの海産物の鮮度が鮮度が良いのか、どのように調理して良いのかわからない。しかし、店員に話しかけるのは難易度が高い場合もある。本サービスでは、このような課題を解決できると考える。
```

2020-09-17 17:04 UTC, mrs1669 requested changes

2020-09-17 17:04 UTC, mrs1669 commented on chapter3.tex
> +    \par COVID-19が収束した後の函館を想定したサービス。環境客に函館の街を楽しんでもらうことや、幅広く函館の街を知ってもらうことがこのサービスの目的である。
環境客ってなんだよ
![居眠りのイラスト（男性）](https://2.bp.blogspot.com/-W3kGdgs5XyU/U2ssJzgFvuI/AAAAAAAAgAg/MSkEgrzfKvo/s400/pose_inemuri.png)

2020-09-17 17:10 UTC, ym223 commented on chapter3.tex
> +        \par 函館は海産物が特産品であるため、函館らしいといえる。
函館のここ、おすすめかも？？？？

2020-09-17 17:14 UTC, ym223 commented on chapter3.tex
> +    \par このサービスはイベントの主催者や出店者、イベントに立ち寄った観光客や地元の人を対象としたサービスであり、立ち寄った観光客や地元民が自身のスマートフォンから手軽にイベントの詳細を知ることがこのサービスの主な機能である。さらにイベントの参加者によるイベントのレビュー機能を考案している。この機能によってイベントの参加者はイベントの主催者やイベントを評価することができる。
立ち寄った客->イベント参加者に変わるのがもにょっとする(´・ω・｀)
観客とかでいいのでは？？
```suggestion
    \par このサービスはイベントの主催者や出店者、イベントに立ち寄った観光客や地元の人を対象としたサービスであり、立ち寄った観光客や地元民が自身のスマートフォンから手軽にイベントの詳細を知ることができる。さらに、イベントの参加者によるイベントのレビュー機能を考案している。この機能によって、イベントの参加者はイベントや主催者を評価することができる。
```

2020-09-17 17:20 UTC, ym223 commented on chapter3.tex
> +    \par このサービスを提供することでイベントの活性化や、イベントが今後も継続することを勧め、函館のさらなる活性化に努めることがこのサービスの目的である。
なんかわかりにくい感じがするのですが、こんな感じはどうでしょうか
```suggestion
    \par このサービスを提供することでイベントの活性化や(今後の)発展に役立て、函館のさらなる活性化につなげることを目的としている。
```

2020-09-17 17:23 UTC, ym223 commented on chapter3.tex
> +    \par 店の近くを通りかかった人のスマホに別の店のクーポンを配って店に呼び込む。呼び込みが成功すると別の店のクーポンを得た人は、その別の店に足を運ぶ。この動作を繰り返すことで函館を活発にする。
> 店に呼び込む
どっちのお店？？なんか説明がわかりにくいような〜〜〜

```suggestion
    \par 店の近くを通りかかった人のスマートフォンに別の店のクーポンを配って店に呼び込む。呼び込みが成功すると別の店のクーポンを得た人は、その別の店に足を運ぶ。この動作を繰り返すことで函館を活発にする。
```

2020-09-17 17:28 UTC, ym223 commented on chapter3.tex
> +    \par 最初のクーポンをもらった店から、他のお店をめぐることで函館全体の活性化につなげ、わらしべ長者のような体験を店に立ち寄った人に与える。
クーポン長者の説明に関してなんだけど、「店に立ち寄った人」とか「通りかかった人」って言い方がなんか、ん〜〜〜てなる(´・ω・｀)
でもしっくり来る言葉は見つかりません(´・ω・｀)
```suggestion
    \par 最初のクーポンをもらった店から、他の店をめぐることで函館全体の活性化につなげる。さらに、わらしべ長者のような体験を店に立ち寄った人に与える。
```

2020-09-17 17:33 UTC, ym223 commented on chapter3.tex
> +        \par 地元民の情報をその場で知る術はなかったが、このサービス提供することで実現可能になる。
```suggestion
        \par 地元民の情報をその場で知る術はなかったが、このサービスを提供することで実現可能になる。
```

2020-09-17 17:34 UTC, ym223 commented
地元住民の言い方もブレブレかも

2020-09-17 17:56 UTC, ym223 commented on chapter3.tex
> +        \par 函館市では、朝市や金森赤レンガ倉庫、五稜郭といった観光地にビーコンが設置されている。このビーコンを使用することで、ユーザーに函館のお店を利用してもらうことができると考えられる。
ここは函館か
```suggestion
        \par 函館では、朝市や金森赤レンガ倉庫、五稜郭といった観光地にビーコンが設置されている。このビーコンを使用することで、ユーザーに函館のお店を利用してもらうことができると考えられる。
```

2020-09-17 17:58 UTC, ym223 commented on chapter3.tex
> +    \par 函館の街中に設置されたビーコンの電波を受信すると、そのビーコンのUUIDに基づいたキャラクターが生成される。ビーコンによって生成されるキャラクターとステータスが異なるため、より強いキャラクターを探し、対戦するゲームである。
```suggestion
    \par 函館の街中に設置されたビーコンの電波を受信すると、そのビーコンのUUIDに基づいたキャラクターが生成される。ビーコンごとに生成されるキャラクターとステータスが異なるため、より強いキャラクターを探し、対戦するゲームである。
```

2020-09-18 05:14 UTC, Ryuku-Hisa approved these changes

2020-09-18 09:05 UTC, kume-negitoro requested changes
ビーコンバトラーの分の提案です。

2020-09-18 09:05 UTC, kume-negitoro commented on chapter3.tex
> +    \par (・ω・｀)
```suggestion
    \item 背景
    \par 街の中には観光地に設置されたものや自動販売機に内蔵されたものなど、様々なビーコンが存在する。それらを活用し、函館に新たな魅力をもたらす新感覚のゲームを開発する。
    \item サービス概要
    \par 函館の街中に設置されたビーコンの電波を受信すると、そのビーコンのUUIDに基づいたキャラクターが生成される。ビーコンごとに生成されるキャラクターとステータスが異なるため、より強いキャラクターを探し、対戦するゲームである。
    \item 目的
    \par 函館に訪れた人や楽しく散策したい人に向けて、ゲームを通してプラスαの魅力を提供すること。
```

2020-09-18 09:17 UTC, santyoume commented on chapter3.tex
> +        \par 手軽に、深く函館について知る機会を提供することで、観光客が増え域内循環が向上される。
```suggestion
        \par 手軽に、深く函館について知る機会を提供することで、観光客が増え域内循環が活性化される。
```

2020-09-18 09:25 UTC, ym223 requested changes

2020-09-18 09:25 UTC, ym223 commented on chapter3.tex
> +    \par COVID-19が収束した後の函館を想定したサービス。環境客に函館の街を楽しんでもらうことや、幅広く函館の街を知ってもらうことがこのサービスの目的である。
```suggestion
    \par COVID-19が収束した後の函館を想定したサービス。観光客に函館の街を楽しんでもらうことや、幅広く函館の街を知ってもらうことがこのサービスの目的である。
```

2020-09-18 09:52 UTC, ym223 commented on chapter3.tex
> +    \par COVID-19が収束した後の函館を想定したサービス。観光客に函館の街を楽しんでもらうことや、幅広く函館の街を知ってもらうことがこのサービスの目的である。
ここだけ体言止めなの気になる。
想定しており、～でもいいかなって思ったけど、一文にすると長いかな？？
```suggestion
    \par COVID-19が収束した後の函館を想定したサービスである。観光客に函館の街を楽しんでもらうことや、幅広く函館の街を知ってもらうことがこのサービスの目的である。
```

2020-09-18 09:53 UTC, ym223 commented on chapter3.tex
> +    \par COVID-19が収束した後の函館を想定したサービス。環境客に函館の街を楽しんでもらうことや、幅広く函館の街を知ってもらうことがこのサービスの目的である。
なおしたよん

2020-09-18 09:54 UTC, ym223 commented on chapter3.tex
> +        \par 見る人によって景色から感じることは違うため、このサービスは同じ景色でも使う人によって異なる単語を作ることができる。
これもなおした

2020-09-18 10:12 UTC, santyoume commented on chapter3.tex
> +    \par (・ω・｀)
書いてみた
```suggestion
    \par 函館には、地元の人もあまり入ったことのないような店が存在する。それらの店をより多くの人が知り、利用してもらえれば函館全体の活性化に繋がるのではないか。
```

2020-09-18 10:20 UTC, ym223 commented on chapter3.tex
> +    \par 店の近くを通りかかった人のスマートフォンに別の店のクーポンを提示して店に呼び込む。呼び込みが成功すると別の店のクーポンを得た人は、その別の店に足を運ぶ。この動作を繰り返すことで函館を活発にする。
活発…？
経済活動を活発にするとかいいね！
```suggestion
    \par 店の近くを通りかかった人のスマートフォンに別の店のクーポンを提示して店に呼び込む。呼び込みが成功すると別の店のクーポンを得た人は、その別の店に足を運ぶ。この動作を繰り返すことで函館を活性化させる。
```

2020-09-18 10:22 UTC, ym223 commented on chapter3.tex
> +    \par 函館はその街並みが美しいことから、観光地としてだけでなく、映画やCMのロケ地としてもよく使用される。しかしながら、函館市ではロケ地を(あんまり推してないよねって書きたい)。
だれか助けて
```suggestion
    \par 函館はその街並みが美しいことから、観光地としてだけでなく、映画やCMのロケ地としてもよく使用される。しかしながら、函館市ではロケ地を(あんまり推してないよねって書きたい)。
```

2020-09-18 10:24 UTC, ym223 commented on chapter3.tex
> +    \par 函館を舞台としたゲームを作ることで、函館の街並みを市外のユーザーにも伝えることができる。また、ゲームを楽しんでもらうことで、実際にゲームの舞台となった場所を訪れてもらうことができると考える。
> 函館を舞台としたゲームを作ることで、函館の街並みを市外のユーザーにも伝えることができる。また、ゲームを楽しんでもらうことで、実際にゲームの舞台となった場所を訪れてもらうことができると考える。

これは目的で合ってる…？

2020-09-18 10:32 UTC, 212naoki reviewed
気になったところを書きました
正直読点は好みのところがあるから色んな人の意見を聞きたいところ

2020-09-18 10:32 UTC, 212naoki commented on chapter3.tex
> +    \par このサービスはイベントの主催者や出店者、イベントに立ち寄った観光客や地元の人を対象としたサービスであり、立ち寄った観光客や地元の人が自身のスマートフォンから手軽にイベントの詳細を知ることがこのサービスの主な機能である。立ち寄った観光客や地元の人が自身のスマートフォンから手軽にイベントの詳細を知ることができる。さらに、イベントに参加した観光客や地元の人によるイベントのレビュー機能
「観光客や地元の人」が何回も出てきて少しくどい気がする…
二回目以降はイベントの参加者とかでもいいかも？

2020-09-18 10:32 UTC, 212naoki commented on chapter3.tex
> +        \par 前例として「Beaconを利用した観光ガイドアプリ」[1]が存在するがこのサービスではイベントの内容だけでなく、イベントの主催者についてや目的なども知ることができる。またイベントをレビューする機能はイベントの主催者と参加者が手軽に交流する機会として新規性があるといえる。
一文が長い気がする

```suggestion
        \par 前例として「Beaconを利用した観光ガイドアプリ」[1]が存在するが、このサービスではイベントの内容だけでなく、イベントの主催者についてや目的なども知ることができる。また、イベントをレビューする機能は、イベントの主催者と参加者が手軽に交流する機会として新規性があるといえる。
```

2020-09-18 10:32 UTC, 212naoki commented on chapter3.tex
> +    \par 最初のクーポンをもらった店から、他のお店をめぐることで函館全体の活性化につなげる。さらに、わらしべ長者のような体験を店に立ち寄った人に与える。
「店」、「お店」の表記ゆれ

```suggestion
    \par 最初のクーポンをもらった店から、他の店をめぐることで函館全体の活性化につなげる。さらに、わらしべ長者のような体験を店に立ち寄った人に与える。
```

2020-09-18 10:32 UTC, 212naoki commented on chapter3.tex
> +    \par 未来大学のライブラリでは、パソコンで蔵書を検索し、パソコンに出力された番号のメモを取る。この番号をもとに本の位置を把握する。このメモを取るというアナログな行為によって検索から本の位置把握までの流れがスムーズではないのが現状である。
一文が長い気がする

```suggestion
    \par 未来大学のライブラリでは、パソコンで蔵書を検索し、パソコンに出力された番号のメモを取る。この番号をもとに本の位置を把握する。このメモを取るというアナログな行為によって、検索から本の位置把握までの流れがスムーズではないのが現状である。
```

2020-09-18 10:32 UTC, 212naoki commented on chapter3.tex
> +        \par このサービスを提供することで、客に店のはしごを促すことができる。はしごを促すことで地域全体の活性化につながる。
「はしごを促すことができる」が2回続いてるのが気になる

```suggestion
        \par このサービスを提供することで、客に店のはしごを促し、地域全体の活性化につながる。
```

2020-09-18 10:32 UTC, 212naoki commented on chapter3.tex
> +    \par 本棚にビーコンを設置し、スマートフォンで電波を受信することで目的の本の位置を把握することができる。送信する情報の中に、本のレビュー機能や講義に適している参考書のおすすめ情報を付加する。
一文が(ry

```suggestion
    \par 本棚にビーコンを設置し、スマートフォンで電波を受信することで、目的の本の位置を把握することができる。送信する情報の中に、本のレビュー機能や、講義に適している参考書のおすすめ情報を付加する。
```

2020-09-18 10:32 UTC, 212naoki commented on chapter3.tex
> +        \par 屋内のお店に訪れる際、屋内の位置情報はGPSでは取得することが難しいのでビーコンでサービスを実現する必要がある。また、ビーコンを用いることでどの店舗にどれくらい滞在したかなどの情報も取得することができるため、ビーコンでの実装をするべきである。
一文が少し長いかも

```suggestion
        \par 屋内のお店に訪れる際、屋内の位置情報はGPSでは取得することが難しいので、ビーコンでサービスを実現する必要がある。また、ビーコンを用いることで、どの店舗にどれくらい滞在したかなどの情報も取得することができるため、ビーコンでの実装をするべきである。
```

2020-09-18 10:32 UTC, 212naoki commented on chapter3.tex
> +    \par サービスを使用することで、探している本の位置把握を簡単にする。また、何か本を借りたいという明確でない目的でライブラリを訪れた人に対してレビュー機能等でお勧めの本を提案することができる。
一文(ry

```suggestion
    \par サービスを使用することで、探している本の位置把握を簡単にする。また、何か本を借りたいという明確でない目的でライブラリを訪れた人に対して、レビュー機能等でお勧めの本を提案することができる。
```

2020-09-18 10:32 UTC, 212naoki commented on chapter3.tex
> +        \par 未来大学向けのサービスであるため函館らしさは薄いと考える。
一文(ry

```suggestion
        \par 未来大学向けのサービスであるため、函館らしさは薄いと考える。
```

2020-09-18 10:32 UTC, 212naoki commented on chapter3.tex
> +        \par GPSは屋内での位置測位の精度が低い。加えてライブラリという小さな範囲となるとGPSの位置把握は困難であると考える。一方、ビーコンを用いた屋内での位置測位は他の屋内でも位置測位と比較すると導入が容易なため、ライブラリへの導入はビーコンが適している。
一文(ry

```suggestion
        \par GPSは屋内での位置測位の精度が低い。加えてライブラリという小さな範囲となると、GPSの位置把握は困難であると考える。一方、ビーコンを用いた屋内での位置測位は、他の屋内でも位置測位と比較すると導入が容易なため、ライブラリへの導入はビーコンが適している。
```

2020-09-18 10:32 UTC, 212naoki commented on chapter3.tex
> +
タイトルが「未来大」で背景が「未来大学」になってるのが少し気になるかも

2020-09-18 10:32 UTC, 212naoki commented on chapter3.tex
> +    \par 地元の人の方はビーコンを持ち、観光客の方はスマートフォンで地元の人を探すことができる。また、ビーコンから受け取る情報は位置だけでなく、対応言語など地元の人の情報を知ることができる。
文章に違和感が少しある気がする(これでもちょっと不自然な気がする…)

```suggestion
    \par 地元の人の方はビーコンを持ち、観光客の方はスマートフォンで地元の人を探すことができる。また、ビーコンから受け取る情報は位置だけでなく、地元の人の対応言語なども知ることができる。
```

2020-09-18 10:32 UTC, 212naoki commented on chapter3.tex
> +        \par 近くにいる人がどこにいるかを探すためにはGPSではなくビーコンが適している。GPSではサービスの利用者以外にも位置が把握されてしまうため、安全性に欠ける。
一文(ry

```suggestion
        \par 近くにいる人がどこにいるかを探すためには、GPSではなくビーコンが適している。GPSではサービスの利用者以外にも位置が把握されてしまうため、安全性に欠ける。
```

2020-09-18 10:32 UTC, 212naoki commented on chapter3.tex
> +    \par ネット用語など、若者を中心に様々な言葉が生まれる現代、言葉の変遷を函館の魅力的な景観から発信することで新しい函館の歩き方を体験できる。
一文(ry

```suggestion
    \par ネット用語など、若者を中心に様々な言葉が生まれる現代、言葉の変遷を函館の魅力的な景観から発信することで、新しい函館の歩き方を体験できる。
```

2020-09-18 10:32 UTC, 212naoki commented on chapter3.tex
> +    \par 観光地や景色の良いところにビーコンを設置し、そのビーコンを受信できる範囲から見えた景色をまだ存在しない新しい言葉で表現し投稿、シェアする。また良いと思った単語に投票することができる。
一文(ry

```suggestion
    \par 観光地や景色の良いところにビーコンを設置し、そのビーコンを受信できる範囲から見えた景色を、まだ存在しない新しい言葉で表現し投稿、シェアする。また良いと思った単語に投票することができる。
```

2020-09-18 10:32 UTC, 212naoki commented on chapter3.tex
> +    \par 街の中には観光地に設置されたものや自動販売機に内蔵されたものなど、様々なビーコンが存在する。それらを活用し、函館に新たな魅力をもたらす新感覚のゲームを開発する。
一文(ry

```suggestion
    \par 街の中には観光地に設置されたものや、自動販売機に内蔵されたものなど、様々なビーコンが存在する。それらを活用し、函館に新たな魅力をもたらす新感覚のゲームを開発する。
```

2020-09-18 10:32 UTC, 212naoki commented on chapter3.tex
> +    \par 函館は海に囲まれた街であり、豊富な海産物に恵まれているという特徴がある。朝市やスーパーには、獲れたてのイカやホッケなど、新鮮な海産物が並ぶ。これらの海産物は飲食店だけでなく、地域住民や観光客からも多く求められている。
ここは地域住民で大丈夫？

2020-09-18 10:40 UTC, yuhei-yama commented on chapter3.tex
> +    \par 函館はその街並みが美しいことから、観光地としてだけでなく、映画やCMのロケ地としてもよく使用される。しかしながら、函館市ではロケ地を(あんまり推してないよねって書きたい)。
```suggestion
    \par 函館はその街並みが美しいことから、観光地としてだけでなく、映画やCMのロケ地としてもよく使用される。しかしながら、函館山など有名な観光地の宣伝に比べ、ロケ地の宣伝が少ないように思える。
```
こんな感じでどうでしょう？

2020-09-18 10:42 UTC, ogi-san commented on chapter3.tex
> +        \par 目的の本がある場合は、本の位置がすぐに把握できるため、以前までの検索結果のメモを取るという手間を省くことができる。特定の分野の参考書などを借りたいなどの場合は、レビュー機能で本の情報を得ることで、分野の中でもどれがおすすめなのかなど、本を選ぶ手助けができる。
「特定の分野の参考書などを借りたいなど」がなどがほぼ連続で書かれていて冗長かな～と思った。
あとこれはただの個人的な感覚なんだけど、「分野の中でもどれがおすすめなのかなど、本を選ぶ手助けができる」が気になった。
```suggestion
        \par 目的の本がある場合は、本の位置がすぐに把握できるため、以前までの検索結果のメモを取るという手間を省くことができる。特定の分野の本を探している場合は、レビュー機能で本の情報を得ることで、おすすめの本を知ることができる。
```

2020-09-18 11:17 UTC, ogi-san commented on chapter3.tex
> +\bunseki{袴田、野間}
フルネームに統一した方が良さげかな？

2020-09-18 11:20 UTC, ym223 commented on chapter3.tex
> +    \par (・ω・｀)
神

2020-09-18 11:21 UTC, ym223 commented on chapter3.tex
> +    \par 函館はその街並みが美しいことから、観光地としてだけでなく、映画やCMのロケ地としてもよく使用される。しかしながら、函館市ではロケ地を(あんまり推してないよねって書きたい)。
天才

2020-09-18 11:22 UTC, ym223 commented on chapter3.tex
> +        \par 目的の本がある場合は、本の位置がすぐに把握できるため、以前までの検索結果のメモを取るという手間を省くことができる。特定の分野の参考書などを借りたいなどの場合は、レビュー機能で本の情報を得ることで、分野の中でもどれがおすすめなのかなど、本を選ぶ手助けができる。
しゅき

2020-09-18 11:25 UTC, ym223 commented on chapter3.tex
> +\bunseki{袴田、野間}
文責に関しては、
・節ごとに名前を書くのか
・連名ありなのか
・フルネームか名字だけか(サンプルで名字だけの箇所もあった)
てところが曖昧で、後でマージしてから？決める？？みたいな話をしたようなしてないような…

2020-09-18 11:26 UTC, ym223 commented on chapter3.tex
> +    \par 函館は海に囲まれた街であり、豊富な海産物に恵まれているという特徴がある。朝市やスーパーには、獲れたてのイカやホッケなど、新鮮な海産物が並ぶ。これらの海産物は飲食店だけでなく、地域住民や観光客からも多く求められている。
なおしたよん

2020-09-18 11:32 UTC, mrs1669 commented on chapter3.tex
> +        \par このサービスを提供することで、客に店のはしごを促すことができる。はしごを促すことで地域全体の活性化につながる。
そもそも、「客のはしご」っていう言葉、「はしごする」っていう慣用表現からちょっと変形して使ってると思うんだけど、報告書にする際は、「店を次から次へと変えること(通称:はしご)を促す」

みたいな感じで、軽く説明があった方がいい気がする

2020-09-18 11:33 UTC, ym223 commented on chapter3.tex
> +    \par このサービスはイベントの主催者や出店者、イベントに立ち寄った観光客や地元の人を対象としたサービスであり、立ち寄った観光客や地元の人が自身のスマートフォンから手軽にイベントの詳細を知ることがこのサービスの主な機能である。立ち寄った観光客や地元の人が自身のスマートフォンから手軽にイベントの詳細を知ることができる。さらに、イベントに参加した観光客や地元の人によるイベントのレビュー機能
なんかねー、個人的に「立ち寄った人」と「参加者」が同じ意味に感じなくて、どっちかといえば「観客」くらいの感覚かなって思ってる。
皆さんどう思います？？？

2020-09-18 11:54 UTC, ym223 commented on chapter3.tex
> +        \par このサービスを提供することで、客に店のはしごを促すことができる。はしごを促すことで地域全体の活性化につながる。
なるほど。変更したほうがいいかもね！
て思ったけど、良い感じの言い回しが見つからない。。。

2020-09-18 11:56 UTC, ym223 commented on chapter3.tex
> +    \par 地域住民や観光客が函館の新鮮な海産物を買う際に、どの海産物の鮮度が良いのか、どのように調理して良いのか分からない。しかし、店員に話しかけるのは難易度が高い場合もある。本サービスでは、このような課題を解決できると考える。
なおしたよん

2020-09-18 12:22 UTC, naonom commented on chapter3.tex
> +        \par このサービスを提供することで、客に店のはしごを促すことができる。はしごを促すことで地域全体の活性化につながる。
客が店を次から次へと移動することを促すで良いかな？

2020-09-18 12:24 UTC, Ryuku-Hisa requested changes
はこだてのここ，おすすめかも　の普遍的な魅力を付け足しました．

2020-09-18 12:24 UTC, Ryuku-Hisa commented on chapter3.tex
> +        \par 函館は海産物が特産品であるため、函館らしいといえる。
```suggestion
        \par 季節や流行の要素を取り入れながら、以前訪れた場所も考慮してルート検索を行うため、函館を隅々まで探索することができる。
```

2020-09-18 13:01 UTC, naonom commented on chapter3.tex
> +
未来大に統一しました。

2020-09-18 13:06 UTC, kume-negitoro requested changes
「未来大学」の修正漏れですね

2020-09-18 13:06 UTC, kume-negitoro commented on chapter3.tex
> +        \par 未来大学向けのサービスであるため、函館らしさは薄いと考える。
```suggestion
        \par 未来大向けのサービスであるため、函館らしさは薄いと考える。
```

2020-09-18 13:18 UTC, kume-negitoro requested changes
「動作」だと具体的な動きを想像してしまうので、ここはもう少し抽象的な感じで良いと思いました。

2020-09-18 13:18 UTC, kume-negitoro commented on chapter3.tex
> +    \par 店の近くを通りかかった人のスマートフォンに別の店のクーポンを提示して店に呼び込む。呼び込みが成功すると別の店のクーポンを得た人は、その別の店に足を運ぶ。この動作を繰り返すことで、函館の経済活動を活発にさせることができると考える。
```suggestion
    \par 店の近くを通りかかった人のスマートフォンに別の店のクーポンを提示して店に呼び込む。呼び込みが成功すると別の店のクーポンを得た人は、その別の店に足を運ぶ。このサイクルを繰り返すことで、函館の経済活動を活発にさせることができると考える。
```

2020-09-18 13:29 UTC, santyoume commented on chapter3.tex
> +        \par 人によって景色から感じることは違うため、このサービスは同じ景色でも使う人によって異なる単語を作ることができる。
```suggestion
        \par 同じ景色でも、使う人によって感性は違うため、異なる単語を作ることができる。
```

2020-09-18 13:29 UTC, kume-negitoro requested changes
少し修正。

2020-09-18 13:29 UTC, kume-negitoro commented on chapter3.tex
> +        \par 人によって景色から感じることは違うため、このサービスは同じ景色でも使う人によって異なる単語を作ることができる。
```suggestion
        \par 人によって景色から感じることは違うため、同じ景色でもサービスを使う人によって、異なる単語を作ることができる。
```

2020-09-18 14:04 UTC, mrs1669 requested changes

2020-09-18 14:04 UTC, mrs1669 commented on chapter3.tex
> +    \par 函館は海に囲まれた街であり、豊富な海産物に恵まれているという特徴がある。朝市やスーパーには、獲れたてのイカやホッケなど、新鮮な海産物が並ぶ。これらの海産物は飲食店だけでなく、地元の人ちや観光客からも多く求められている。
```suggestion
    \par 函館は海に囲まれた街であり、豊富な海産物に恵まれているという特徴がある。朝市やスーパーには、獲れたてのイカやホッケなど、新鮮な海産物が並ぶ。これらの海産物は飲食店だけでなく、地元の人たちや観光客からも多く求められている。
```

2020-09-18 15:04 UTC, mrs1669 commented on chapter3.tex
> +    \par 函館には、地元の人もあまり入ったことのないような店が存在する。それらの店をより多くの人が知り、利用してもらえれば函館全体の活性化につながると考える。
「あまり」，「ような」，「それら」なんかぽわ～んってしない？
![ミサワ](https://livedoor.blogimg.jp/jigokuno_misawa/imgs/9/4/94e18515.gif)

2020-09-18 15:05 UTC, Ryuku-Hisa approved these changes

2020-09-18 15:13 UTC, mrs1669 commented on chapter3.tex
> +    \par 函館には有名な店はもちろん、昔ながらのローカルなお店もたくさんある。観光客はそれら全ての魅力に気づくことができず、函館旅行を満喫できているとはいえない。
有名な店はもちろん、昔ながらのローカルな「お」店も
ローカルな店には優しいんすね

```suggestion
    \par 函館には有名な店はもちろん、昔ながらのローカルな店もたくさんある。観光客はそれら全ての魅力に気づくことができず、函館旅行を満喫できているとはいえない。
```

2020-09-18 15:13 UTC, mrs1669 commented on chapter3.tex
> +        \par 函館には様々な観光名所がある。また、函館には地元ならではのお店もたくさん存在するため、函館らしいといえる。
```suggestion
        \par 函館には様々な観光名所がある。また、函館には地元ならではの店もたくさん存在するため、函館らしいといえる。
```

2020-09-18 15:14 UTC, mrs1669 commented on chapter3.tex
> +        \par 屋内のお店に訪れる際、屋内の位置情報はGPSでは取得することが難しいので、ビーコンでサービスを実現する必要がある。また、ビーコンを用いることで、どの店舗にどれくらい滞在したかなどの情報も取得することができるため、ビーコンでの実装をするべきである。
```suggestion
        \par 屋内の店に訪れる際、屋内の位置情報はGPSでは取得することが難しいので、ビーコンでサービスを実現する必要がある。また、ビーコンを用いることで、どの店舗にどれくらい滞在したかなどの情報も取得することができるため、ビーコンでの実装をするべきである。
```

2020-09-18 15:19 UTC, mrs1669 commented on chapter3.tex
> +        \par 函館には様々な観光名所がある。また、函館には地元ならではのお店もたくさん存在するため、函館らしいといえる。
77行 ,91行目 は観光地になってるんだけど，観光名所とはなんかちがうん？ん？
![エンジニアを褒めるネコ:進捗ダメです](https://raw.githubusercontent.com/fukayatsu/lttm-crx/master/vendor/%E3%82%A8%E3%83%B3%E3%82%B8%E3%83%8B%E3%82%A2%E3%82%92%E8%A4%92%E3%82%81%E3%82%8B%E3%83%8D%E3%82%B3/06_%E9%80%B2%E6%8D%97%E3%83%80%E3%83%A1%E3%81%A7%E3%81%99.png) 

```suggestion
        \par 函館には様々な観光地がある。また、函館には地元ならではの店もたくさん存在するため、函館らしいといえる。
```

2020-09-18 15:21 UTC, mrs1669 commented on chapter3.tex
> +        \par 函館には様々な観光名所がある。また、函館には地元ならではの店もたくさん存在するため、函館らしいといえる。
77行 ,91行目 は観光地になってるんだけど，観光名所とはなんかちがうん？ん？
![エンジニアを褒めるネコ:進捗ダメです](https://raw.githubusercontent.com/fukayatsu/lttm-crx/master/vendor/%E3%82%A8%E3%83%B3%E3%82%B8%E3%83%8B%E3%82%A2%E3%82%92%E8%A4%92%E3%82%81%E3%82%8B%E3%83%8D%E3%82%B3/06_%E9%80%B2%E6%8D%97%E3%83%80%E3%83%A1%E3%81%A7%E3%81%99.png) 
```suggestion
        \par 函館には様々な観光地がある。また、函館には地元ならではの店もたくさん存在するため、函館らしいといえる。
```

2020-09-18 15:24 UTC, kume-negitoro requested changes
細かいんですけど確認お願いします。

2020-09-18 15:24 UTC, kume-negitoro commented on chapter3.tex
> +    \par 地元の人や観光客が函館の新鮮な海産物を買う際に、どの海産物の鮮度が良いのか、どのように調理して良いのかわからない。しかし、店員に話しかけるのは抵抗を感じる場合もある。本サービスでは、このような課題を解決できると考える。
```suggestion
    \par 地元の人や観光客が函館の新鮮な海産物を買う際に、どの海産物の鮮度が良いのか、どのように調理して良いのかわからない。しかし、店員に話しかけることに抵抗を感じる場合もある。本サービスでは、このような課題を解決できると考える。
```

2020-09-18 15:26 UTC, kume-negitoro approved these changes
LGTMです！

2020-09-18 15:29 UTC, mrs1669 commented on chapter3.tex
> +        \par 専門的な知識が不必要になるため、幅広いユーザーに永続的に使用されると考えられる。
- 不変的
- 永続的
- 継続的

ってどうちがうんだろうね？よくわかんねぇや

2020-09-18 15:29 UTC, mrs1669 commented on chapter3.tex
> +        \par 定期的に生成されるキャラクターを更新するため、継続的にプレイすることができる。また、観光をより楽しむことができるようになると考える。
- 不変的
- 永続的
- 継続的

ってどうちがうんだろうね？よくわかんねぇや

2020-09-18 15:32 UTC, Ryuku-Hisa approved these changes

2020-09-18 15:32 UTC, mrs1669 commented on chapter3.tex
> +        \par 函館では、朝市や金森赤レンガ倉庫、五稜郭といった観光地にビーコンが設置されている。このビーコンを使用することで、ユーザーに函館のお店を利用してもらうことができると考えられる。
「お」？

```suggestion
        \par 函館では、朝市や金森赤レンガ倉庫、五稜郭といった観光地にビーコンが設置されている。このビーコンを使用することで、ユーザーに函館の店を利用してもらうことができると考えられる。
```

2020-09-18 15:35 UTC, Ryuku-Hisa approved these changes
LGTM

2020-09-18 15:35 UTC, ogi-san approved these changes

2020-09-18 15:36 UTC, D1438 approved these changes
あまり参加してなくてごめんなさい。LGTMです！

2020-09-18 15:36 UTC, ym223 approved these changes

2020-09-18 15:37 UTC, mrs1669 approved these changes
![エンジニアを褒めるネコ:LGTM](https://raw.githubusercontent.com/fukayatsu/lttm-crx/master/vendor/%E3%82%A8%E3%83%B3%E3%82%B8%E3%83%8B%E3%82%A2%E3%82%92%E8%A4%92%E3%82%81%E3%82%8B%E3%83%8D%E3%82%B3/01_LGTM.png)

2020-09-18 15:37 UTC, merged