Initial commit
beaconFUN/mid-report2020 pull request #13
Opened 2020-09-17 13:14 UTC by yuhei-yama

遅れてすみません！
第2章提供サービスの考案プロセスを書きました。
文章全体のチェックをお願い致します。

2020-09-17 13:39 UTC, mrs1669 commented
![エンジニアを褒めるネコ:なるほどわからん](https://raw.githubusercontent.com/fukayatsu/lttm-crx/master/vendor/%E3%82%A8%E3%83%B3%E3%82%B8%E3%83%8B%E3%82%A2%E3%82%92%E8%A4%92%E3%82%81%E3%82%8B%E3%83%8D%E3%82%B3/36_%E3%81%AA%E3%82%8B%E3%81%BB%E3%81%A9%E3%82%8F%E3%81%8B%E3%82%89%E3%82%93.png)

2020-09-17 13:46 UTC, mrs1669 commented
![iOS のファイル](https://user-images.githubusercontent.com/40351476/93479745-a1207d80-f937-11ea-90a2-8e42eebd852c.gif)

2020-09-17 13:56 UTC, mrs1669 requested changes

2020-09-17 13:56 UTC, mrs1669 commented on chapter2.tex
> +本プロジェクトの提供サービス考案までのプロセスは、大きく 4 つに分かれる。1つ目は、フィールドワークである。実際に函館を見て回り、まちにある課題を探した。2つ目はブレーンストーミングとKJ法（以下BSKJ法）である。フィールドワークで感じたことや、これまでの自身の体験をもとに函館の街に存在する課題を割り出し、それらをグルーピングした。3つ目はオープン・スペース・テクノロジー（以下OST）である
`大きく 4 つに分かれる`
大きくの後にスペースが入ってる

2020-09-17 14:07 UTC, mrs1669 requested changes
![ミサワ](https://livedoor.blogimg.jp/jigokuno_misawa/imgs/4/7/4782fa0f.gif)

2020-09-17 14:07 UTC, mrs1669 commented on chapter2.tex
> +実地調査は、プレ実施したのちに本実施した。プレ実施では、函館山で6月19日に実施した。本実施では、2.2.1節で述べた5つの地区で5つのグループに分かれて6月21日に実施した。ただし、新型コロナ感染への対策として体調の管理やマスク着用必須、人混みや他人との接触・会話を避けるなどに注意することとした。五稜郭地区では、五稜郭公園、五稜郭タワー、五稜郭交差点地下横断歩道、千代台公園、JR五稜郭駅、函館
`ただし、新型コロナ感染への対策として`
https://github.com/beaconFUN/mid-report2020/blob/draft/chapter6/chapter6.tex
の52行目のコロナに関する記述と整合性を図りたい

2020-09-17 14:07 UTC, mrs1669 commented on chapter2.tex
> +調査で得た情報をまとめて他の班と共有するため、各グループでフィールドワーク中に気づいた点について、Google Jamboardに写真や付箋を用いて書き出した。そして、書き出した写真や付箋をグループ分けした。その後、全グループでzoomに集まり、各グループのGoogle Jamboardを見せながら結果を共有した。プレ調査では、函館山を訪れた。調査の結果、展望台やロープウェイにはビーコンが設置さ
`時短営業や観光客の減少などのコロナウイルスの影響`
20行目と同様

2020-09-17 14:10 UTC, 212naoki reviewed
一部全角

2020-09-17 14:10 UTC, 212naoki commented on chapter2.tex
> +ハッカソンはハックとマラソンを掛け合わせた造語でチームを作成し、短期間でサービスやシステム、アプリケーションを開発し、成果を競うイベントの一種である。私たちはこのハッカソンを2回のアイデア出しに用いた。1回目は、4人１グループを作成し、90分の時間制限を設けてアイデアを出しを行った。2回目は参加者が順番に出題し、3分の時間制限を設けてお題に沿ったアイデア出しを行った。この方式ではそれぞれがアイデ
```suggestion
ハッカソンはハックとマラソンを掛け合わせた造語でチームを作成し、短期間でサービスやシステム、アプリケーションを開発し、成果を競うイベントの一種である。私たちはこのハッカソンを2回のアイデア出しに用いた。1回目は、4人1グループを作成し、90分の時間制限を設けてアイデアを出しを行った。2回目は参加者が順番に出題し、3分の時間制限を設けてお題に沿ったアイデア出しを行った。この方式ではそれぞれがアイデアの絵を書いてメンバーにイメージを共有しながら進めていった。
```

2020-09-17 14:10 UTC, 212naoki commented on chapter2.tex
> +KJ法ですべての班のアイデアのグルーピングを行った結果からブラッシュアップを行うにあたりアイデアの絞り込みを行った。メンバーは１～4点の計9点を持ち点として各々が興味のあるアイデアに投票を行い、絞りこみを行った。その結果、中間発表の時点では「お店とビーコン」、「観光」、「隠れスポット」、「施設とビーコン」の4つの項目に絞ることができた。その後、これらのアイデアに3～4人割り振って、アイデアのブラ
```suggestion
KJ法ですべての班のアイデアのグルーピングを行った結果からブラッシュアップを行うにあたりアイデアの絞り込みを行った。メンバーは1～4点の計10点を持ち点として各々が興味のあるアイデアに投票を行い、絞りこみを行った。その結果、中間発表の時点では「お店とビーコン」、「観光」、「隠れスポット」、「施設とビーコン」の4つの項目に絞ることができた。その後、これらのアイデアに3～4人割り振って、アイデアのブラッシュアップを行った。各グループでのブラッシュアップの内容をesaにまとめて学生と教員間でレビューを行い、それを参考にして、さらにブラッシュアップを行っていった。今後は中間発表時のアイデアと夏季休業中のアイデア出しでのアイデアを「函館らしさ」「ビーコンである理由」「必要性」「新規性」「不変的な魅力」の5つの観点でブラッシュアップを行い、最終的なアイデアを出していく。
```

2020-09-17 14:21 UTC, D1438 commented on chapter2.tex
> +本プロジェクトの提供サービス考案までのプロセスは、大きく 4 つに分かれる。1つ目は、フィールドワークである。実際に函館を見て回り、まちにある課題を探した。2つ目はブレーンストーミングとKJ法（以下BSKJ法）である。フィールドワークで感じたことや、これまでの自身の体験をもとに函館の街に存在する課題を割り出し、それらをグルーピングした。3つ目はオープン・スペース・テクノロジー（以下OST）である
`実際に函館を見て回り、まちにある課題を〜`
その後に
`函館の街`
と書いてあるので”街”にした方がいいと思う。
```suggestion
本プロジェクトの提供サービス考案までのプロセスは、大きく 4 つに分かれる。1つ目は、フィールドワークである。実際に函館を見て回り、まちにある課題を探した。2つ目はブレーンストーミングとKJ法（以下BSKJ法）である。フィールドワークで感じたことや、これまでの自身の体験をもとに函館の街に存在する課題を割り出し、それらをグルーピングした。3つ目はオープン・スペース・テクノロジー（以下OST）である。OSTを通してBSKJ法で出てきた課題やそれを解決する方法について議論し、アイデアの解像度を上げた。4つ目はブラッシュアップである。BSKJやOSTを通して出たアイデアをより深堀りし、必要性や新規性などを考慮し、アイデアのブラッシュアップを行った。その他にもプロジェクトのロゴの制作や、ビーコンが使われたサービスを考案するにあたって必要な情報を入手する事前調査などの内容も説明する。
```
```suggestion
本プロジェクトの提供サービス考案までのプロセスは、大きく 4 つに分かれる。1つ目は、フィールドワークである。実際に函館を見て回り、まちにある課題を探した。2つ目はブレーンストーミングとKJ法（以下BSKJ法）である。フィールドワークで感じたことや、これまでの自身の体験をもとに函館の街に存在する課題を割り出し、それらをグルーピングした。3つ目はオープン・スペース・テクノロジー（以下OST）である。OSTを通してBSKJ法で出てきた課題やそれを解決する方法について議論し、アイデアの解像度を上げた。4つ目はブラッシュアップである。BSKJやOSTを通して出たアイデアをより深堀りし、必要性や新規性などを考慮し、アイデアのブラッシュアップを行った。その他にもプロジェクトのロゴの制作や、ビーコンが使われたサービスを考案するにあたって必要な情報を入手する事前調査などの内容も説明する。
```

2020-09-17 14:28 UTC, yuhei-yama commented on chapter2.tex
> +本プロジェクトの提供サービス考案までのプロセスは、大きく 4 つに分かれる。1つ目は、フィールドワークである。実際に函館を見て回り、まちにある課題を探した。2つ目はブレーンストーミングとKJ法（以下BSKJ法）である。フィールドワークで感じたことや、これまでの自身の体験をもとに函館の街に存在する課題を割り出し、それらをグルーピングした。3つ目はオープン・スペース・テクノロジー（以下OST）である
修正しました！

2020-09-17 14:30 UTC, yuhei-yama commented on chapter2.tex
> +実地調査は、プレ実施したのちに本実施した。プレ実施では、函館山で6月19日に実施した。本実施では、2.2.1節で述べた5つの地区で5つのグループに分かれて6月21日に実施した。ただし、新型コロナ感染への対策として体調の管理やマスク着用必須、人混みや他人との接触・会話を避けるなどに注意することとした。五稜郭地区では、五稜郭公園、五稜郭タワー、五稜郭交差点地下横断歩道、千代台公園、JR五稜郭駅、函館
修正しました！

2020-09-17 14:30 UTC, yuhei-yama commented on chapter2.tex
> +調査で得た情報をまとめて他の班と共有するため、各グループでフィールドワーク中に気づいた点について、Google Jamboardに写真や付箋を用いて書き出した。そして、書き出した写真や付箋をグループ分けした。その後、全グループでzoomに集まり、各グループのGoogle Jamboardを見せながら結果を共有した。プレ調査では、函館山を訪れた。調査の結果、展望台やロープウェイにはビーコンが設置さ
修正しました！

2020-09-17 14:30 UTC, yuhei-yama commented on chapter2.tex
> +ハッカソンはハックとマラソンを掛け合わせた造語でチームを作成し、短期間でサービスやシステム、アプリケーションを開発し、成果を競うイベントの一種である。私たちはこのハッカソンを2回のアイデア出しに用いた。1回目は、4人１グループを作成し、90分の時間制限を設けてアイデアを出しを行った。2回目は参加者が順番に出題し、3分の時間制限を設けてお題に沿ったアイデア出しを行った。この方式ではそれぞれがアイデ
修正しました！

2020-09-17 14:30 UTC, yuhei-yama commented on chapter2.tex
> +KJ法ですべての班のアイデアのグルーピングを行った結果からブラッシュアップを行うにあたりアイデアの絞り込みを行った。メンバーは１～4点の計9点を持ち点として各々が興味のあるアイデアに投票を行い、絞りこみを行った。その結果、中間発表の時点では「お店とビーコン」、「観光」、「隠れスポット」、「施設とビーコン」の4つの項目に絞ることができた。その後、これらのアイデアに3～4人割り振って、アイデアのブラ
修正しました！

2020-09-17 14:31 UTC, yuhei-yama commented on chapter2.tex
> +本プロジェクトの提供サービス考案までのプロセスは、大きく 4 つに分かれる。1つ目は、フィールドワークである。実際に函館を見て回り、まちにある課題を探した。2つ目はブレーンストーミングとKJ法（以下BSKJ法）である。フィールドワークで感じたことや、これまでの自身の体験をもとに函館の街に存在する課題を割り出し、それらをグルーピングした。3つ目はオープン・スペース・テクノロジー（以下OST）である
修正しました！

2020-09-17 14:32 UTC, Ryuku-Hisa requested changes

2020-09-17 14:34 UTC, yuhei-yama commented on chapter2.tex
> +本プロジェクトの提供サービス考案までのプロセスは、大きく 4 つに分かれる。1つ目は、フィールドワークである。実際に函館を見て回り、まちにある課題を探した。2つ目はブレーンストーミングとKJ法（以下BSKJ法）である。フィールドワークで感じたことや、これまでの自身の体験をもとに函館の街に存在する課題を割り出し、それらをグルーピングした。3つ目はオープン・スペース・テクノロジー（以下OST）である
修正しました！

2020-09-17 14:41 UTC, mrs1669 commented on chapter2.tex
> +調査で得た情報をまとめて他の班と共有するため、各グループでフィールドワーク中に気づいた点について、Google Jamboardに写真や付箋を用いて書き出した。そして、書き出した写真や付箋をグループ分けした。その後、全グループでzoomに集まり、各グループのGoogle Jamboardを見せながら結果を共有した。プレ調査では、函館山を訪れた。調査の結果、展望台やロープウェイにはビーコンが設置さ
https://github.com/beaconFUN/mid-report2020/pull/11/files
の4行目のように
Chapter4はZoomを頭文字Zを大文字にしちゃったけどどうしよう

2020-09-17 14:46 UTC, yuhei-yama commented on chapter2.tex
> +調査で得た情報をまとめて他の班と共有するため、各グループでフィールドワーク中に気づいた点について、Google Jamboardに写真や付箋を用いて書き出した。そして、書き出した写真や付箋をグループ分けした。その後、全グループでzoomに集まり、各グループのGoogle Jamboardを見せながら結果を共有した。プレ調査では、函館山を訪れた。調査の結果、展望台やロープウェイにはビーコンが設置さ
ありがとう！大文字に変更します！

2020-09-17 14:52 UTC, mrs1669 commented on chapter2.tex
> +調査で得た情報をまとめて他の班と共有するため、各グループでフィールドワーク中に気づいた点について、Google Jamboardに写真や付箋を用いて書き出した。そして、書き出した写真や付箋をグループ分けした。その後、全グループでzoomに集まり、各グループのGoogle Jamboardを見せながら結果を共有した。プレ調査では、函館山を訪れた。調査の結果、展望台やロープウェイにはビーコンが設置さ
おなじ行なんだけど、中盤の
`2.2.1節で記載した５地区を`
の５が全角なのは仕様かな？

2020-09-17 15:05 UTC, yuhei-yama commented on chapter2.tex
> +調査で得た情報をまとめて他の班と共有するため、各グループでフィールドワーク中に気づいた点について、Google Jamboardに写真や付箋を用いて書き出した。そして、書き出した写真や付箋をグループ分けした。その後、全グループでzoomに集まり、各グループのGoogle Jamboardを見せながら結果を共有した。プレ調査では、函館山を訪れた。調査の結果、展望台やロープウェイにはビーコンが設置さ
すまない！
半角に直しました

2020-09-17 15:27 UTC, mrs1669 reviewed
とりあえず変なところはなさそう

2020-09-17 15:27 UTC, mrs1669 approved these changes

2020-09-18 05:14 UTC, Ryuku-Hisa submitted a review, later dismissed

2020-09-18 05:25 UTC, D1438 commented
61行目の"メンバーは１～4点の計10点を持ち点として各々〜”の１の全角だけでも直しておいた方がいいと思う。

2020-09-18 05:58 UTC, yuhei-yama commented
ありがとう！
指摘箇所の数字は半角修正しました！

2020-09-18 08:21 UTC, kume-negitoro requested changes
注視だと、「じっと見つめる」みたいなイメージで違和感があるかも？

2020-09-18 08:21 UTC, kume-negitoro commented on chapter2.tex
> +函館やその周辺の地域に存在する問題や課題を調査し、把握するためにフィールドワークをおこなった。はじめに、函館の地域を大きく5つに分け、「五稜郭」「赤川・美原・昭和・富岡」「函館駅・西部地区」「七飯・北斗」「空港・湯の川」の5地域のイメージを、ブレインストーミングをおこなって書き出した。そして、書き出した各イメージについて様々な視点からグルーピングをおこない、実地調査をおこなう際に注視する点を確認
```suggestion
函館やその周辺の地域に存在する問題や課題を調査し、把握するためにフィールドワークをおこなった。はじめに、函館の地域を大きく5つに分け、「五稜郭」「赤川・美原・昭和・富岡」「函館駅・西部地区」「七飯・北斗」「空港・湯の川」の5地域のイメージを、ブレインストーミングをおこなって書き出した。そして、書き出した各イメージについて様々な視点からグルーピングをおこない、実地調査をおこなう際に注目する点を確認した。その後、各地域の実地調査をおこなう3人1組のグループを編成し、実地調査をおこなった。
```

2020-09-18 08:30 UTC, yuhei-yama commented on chapter2.tex
> +函館やその周辺の地域に存在する問題や課題を調査し、把握するためにフィールドワークをおこなった。はじめに、函館の地域を大きく5つに分け、「五稜郭」「赤川・美原・昭和・富岡」「函館駅・西部地区」「七飯・北斗」「空港・湯の川」の5地域のイメージを、ブレインストーミングをおこなって書き出した。そして、書き出した各イメージについて様々な視点からグルーピングをおこない、実地調査をおこなう際に注視する点を確認
ありがとう！注視から注目に変更しました！

2020-09-18 08:35 UTC, kume-negitoro requested changes
「を」の重複が気になりました。

2020-09-18 08:35 UTC, kume-negitoro commented on chapter2.tex
> +本プロジェクトでは、プロジェクトの特徴やイメージを表現するため、加えて議論の練習と、メンバー全員の一体感を生むために、今年度のプロジェクトのロゴを制作した。ロゴの制作には3週間の時間を要し、決定に至った。まず初めに、メンバー全員がロゴ案を1案以上を考案してロゴの発表会をおこない、それぞれの案についてレビューをおこなった。この段階ではそれぞれの案の良いところだけを伝える形式をとった。ここで受けたレ
```suggestion
本プロジェクトでは、プロジェクトの特徴やイメージを表現するため、加えて議論の練習と、メンバー全員の一体感を生むために、今年度のプロジェクトのロゴを制作した。ロゴの制作には3週間の時間を要し、決定に至った。まず初めに、メンバー全員がロゴ案を1案以上考案してロゴの発表会をおこない、それぞれの案についてレビューをおこなった。この段階ではそれぞれの案の良いところだけを伝える形式をとった。ここで受けたレビューと、他のメンバーのロゴデザインを参考に、各自ロゴの改善をし、2回目の発表会をおこなった。この発表会のレビューでは、良いところと改善点の指摘を含めたレビューをおこない、その後投票によって4つのロゴ案に絞り込んだ。このレビューをもとに、再度ロゴの改善をおこない3回目の発表会をおこなった。この発表会ののち、「函館らしさ」、「ビーコンらしさ」を考慮したうえで、メンバー、TA、先生を交えて最終投票をおこなって今年度のロゴを決定した。その後、ロゴに関するワーキンググループを結成し、デザイン原案の改善をおこなった。ロゴデザインの最終版とロゴ使用に関するガイドラインを作成した。
```

2020-09-18 08:41 UTC, yuhei-yama commented on chapter2.tex
> +本プロジェクトでは、プロジェクトの特徴やイメージを表現するため、加えて議論の練習と、メンバー全員の一体感を生むために、今年度のプロジェクトのロゴを制作した。ロゴの制作には3週間の時間を要し、決定に至った。まず初めに、メンバー全員がロゴ案を1案以上を考案してロゴの発表会をおこない、それぞれの案についてレビューをおこなった。この段階ではそれぞれの案の良いところだけを伝える形式をとった。ここで受けたレ
「を」の重複削除しました！

2020-09-18 08:43 UTC, kume-negitoro submitted a review, later dismissed
LGTM

2020-09-18 08:43 UTC, mrs1669 requested changes

2020-09-18 08:43 UTC, mrs1669 commented on chapter2.tex
> +実地調査は、プレ実施したのちに本実施した。プレ実施では、函館山で6月19日に実施した。本実施では、2.2.1節で述べた5つの地区で5つのグループに分かれて6月21日に実施した。ただし、COVID-19感染への対策として体調の管理やマスク着用必須、人混みや他人との接触・会話を避けるなどに注意することとした。五稜郭地区では、五稜郭公園、五稜郭タワー、五稜郭交差点地下横断歩道、千代台公園、JR五稜郭駅
https://github.com/beaconFUN/mid-report2020/pull/12/files
の204行目「金森赤レンガ倉庫」と「金森倉庫」で表記ゆれがあります
どっちに統一すべきかはしらん！！
![ミサワ](https://livedoor.blogimg.jp/jigokuno_misawa/imgs/3/5/358dacdc.gif)

2020-09-18 08:50 UTC, yuhei-yama commented on chapter2.tex
> +実地調査は、プレ実施したのちに本実施した。プレ実施では、函館山で6月19日に実施した。本実施では、2.2.1節で述べた5つの地区で5つのグループに分かれて6月21日に実施した。ただし、COVID-19感染への対策として体調の管理やマスク着用必須、人混みや他人との接触・会話を避けるなどに注意することとした。五稜郭地区では、五稜郭公園、五稜郭タワー、五稜郭交差点地下横断歩道、千代台公園、JR五稜郭駅
金森赤レンガ倉庫に変更しました！

2020-09-18 08:50 UTC, mrs1669 commented on chapter2.tex
> +ハッカソンはハックとマラソンを掛け合わせた造語で、チームを作成し、短期間でサービスやシステム、アプリケーションを開発し、成果を競うイベントの一種である。私たちはこのハッカソンを2回のアイデア出しに用いた。以下ハッカソン方式と呼ぶ。1回目は、4人1グループを作成し、90分の時間制限を設けてアイデアを出しをおこなった。2回目は参加者が順番に出題し、3分の時間制限を設けてお題に沿ったアイデア出しをおこ
```suggestion
ハッカソンはハックとマラソンを掛け合わせた造語で、チームを作成し、短期間でサービスやシステム、アプリケーションを開発し、成果を競うイベントの一種である。私たちはこのハッカソンを2回のアイデア出しに用いた。以下ハッカソン方式と呼ぶ。1回目は、4人1グループを作成し、90分の時間制限を設けてアイデアを出しをおこなった。2回目は参加者が順番に出題し、5分の時間制限を設けてお題に沿ったアイデア出しをおこなった。この方式ではそれぞれがアイデアの絵を書いてメンバーにイメージを共有しながら進めていった。
```
5分にするんじゃなかったっけ？
![ミサワ](https://livedoor.blogimg.jp/jigokuno_misawa/imgs/b/e/be6bbadc.gif)

2020-09-18 08:58 UTC, mrs1669 requested changes

2020-09-18 08:58 UTC, mrs1669 commented on chapter2.tex
> +本プロジェクトでは、プロジェクトの特徴やイメージを表現するため、加えて議論の練習と、メンバー全員の一体感を生むために、今年度のプロジェクトのロゴを制作した。ロゴの制作には3週間の時間を要し、決定に至った。まず初めに、メンバー全員がロゴ案を1案以上考案してロゴの発表会をおこない、それぞれの案についてレビューをおこなった。この段階ではそれぞれの案の良いところだけを伝える形式をとった。ここで受けたレビ
10行目はひらがなの「はじめに」なのにここは漢字になってます．
```suggestion
本プロジェクトでは、プロジェクトの特徴やイメージを表現するため、加えて議論の練習と、メンバー全員の一体感を生むために、今年度のプロジェクトのロゴを制作した。ロゴの制作には3週間の時間を要し、決定に至った。まずはじめに、メンバー全員がロゴ案を1案以上考案してロゴの発表会をおこない、それぞれの案についてレビューをおこなった。この段階ではそれぞれの案の良いところだけを伝える形式をとった。ここで受けたレビューと、他のメンバーのロゴデザインを参考に、各自ロゴの改善をし、2回目の発表会をおこなった。この発表会のレビューでは、良いところと改善点の指摘を含めたレビューをおこない、その後投票によって4つのロゴ案に絞り込んだ。このレビューをもとに、再度ロゴの改善をおこない3回目の発表会をおこなった。この発表会ののち、「函館らしさ」、「ビーコンらしさ」を考慮したうえで、メンバー、TA、先生を交えて最終投票をおこなって今年度のロゴを決定した。その後、ロゴに関するワーキンググループを結成し、デザイン原案の改善をおこなった。ロゴデザインの最終版とロゴ使用に関するガイドラインを作成した。
```
![ミサワ](https://livedoor.blogimg.jp/jigokuno_misawa/imgs/0/c/0c4bd455.gif)

2020-09-18 09:03 UTC, mrs1669 requested changes
![ミサワ](https://livedoor.blogimg.jp/jigokuno_misawa/imgs/4/4/44e13b65-s.gif)

2020-09-18 09:03 UTC, mrs1669 commented on chapter2.tex
> +実地調査は、プレ実施したのちに本実施した。プレ実施では、函館山で6月19日に実施した。本実施では、2.2.1節で述べた5つの地区で5つのグループに分かれて6月21日に実施した。ただし、COVID-19感染への対策として体調の管理やマスク着用必須、人混みや他人との接触・会話を避けるなどに注意することとした。五稜郭地区では、五稜郭公園、五稜郭タワー、五稜郭交差点地下横断歩道、千代台公園、JR五稜郭駅
「2.2.1節で述べた5つの地区」
25行目「2.2.1節で記載した5地区」
との表記ゆれ

2020-09-18 09:03 UTC, mrs1669 commented on chapter2.tex
> +調査で得た情報をまとめて他の班と共有するため、各グループでフィールドワーク中に気づいた点について、Google Jamboardに写真や付箋を用いて書き出した。そして、書き出した写真や付箋をグループ分けした。その後、全グループでZoomに集まり、各グループのGoogle Jamboardを見せながら結果を共有した。プレ調査では、函館山を訪れた。調査の結果、展望台やロープウェイにはビーコンが設置さ
「2.2.1節で記載した5地区」
20行目「2.2.1節で述べた5つの地区」
との表記ゆれ

2020-09-18 09:06 UTC, mrs1669 commented on chapter2.tex
> +調査で得た情報をまとめて他の班と共有するため、各グループでフィールドワーク中に気づいた点について、Google Jamboardに写真や付箋を用いて書き出した。そして、書き出した写真や付箋をグループ分けした。その後、全グループでZoomに集まり、各グループのGoogle Jamboardを見せながら結果を共有した。プレ調査では、函館山を訪れた。調査の結果、展望台やロープウェイにはビーコンが設置さ
後半の
`五稜郭周辺や函館駅周辺、湯の川周辺`
周辺, 周辺うるさくね？

2020-09-18 09:16 UTC, mrs1669 requested changes
![ミサワ](https://livedoor.blogimg.jp/jigokuno_misawa/imgs/2/3/237a0422.gif)

2020-09-18 09:16 UTC, mrs1669 commented on chapter2.tex
> +本プロジェクトでは、プロジェクトの特徴やイメージを表現するため、加えて議論の練習と、メンバー全員の一体感を生むために、今年度のプロジェクトのロゴを制作した。ロゴの制作には3週間の時間を要し、決定に至った。まずはじめに、メンバー全員がロゴ案を1案以上考案してロゴの発表会をおこない、それぞれの案についてレビューをおこなった。この段階ではそれぞれの案の良いところだけを伝える形式をとった。ここで受けたレ
```suggestion
本プロジェクトでは、プロジェクトの特徴やイメージを表現するため、加えて議論の練習と、メンバー全員の一体感を生むために、今年度のプロジェクトのロゴを制作した。ロゴの制作には3週間の時間を要し、決定に至った。まずはじめに、メンバー全員がロゴ案を1案以上考案してロゴの発表会をおこない、それぞれの案についてレビューをおこなった。この段階ではそれぞれの案の良いところだけを伝える形式をとった。ここで受けたレビューと、他のメンバーのロゴデザインを参考に、各自ロゴの改善をし、2回目の発表会をおこなった。この発表会のレビューでは、良いところと改善点の指摘を含めたレビューをおこない、その後投票によって4つのロゴ案に絞り込んだ。このレビューをもとに、再度ロゴの改善をおこない3回目の発表会をおこなった。この発表会の後、「函館らしさ」、「ビーコンらしさ」を考慮したうえで、メンバー、TA、先生を交えて最終投票をおこなって今年度のロゴを決定した。その後、ロゴに関するワーキンググループを結成し、デザイン原案の改善をおこなった。ロゴデザインの最終版とロゴ使用に関するガイドラインを作成した。
```
ここともう一箇所以外全部漢字になってる

2020-09-18 09:16 UTC, mrs1669 commented on chapter2.tex
> +本プロジェクトでは、プロジェクトの特徴やイメージを表現するため、加えて議論の練習と、メンバー全員の一体感を生むために、今年度のプロジェクトのロゴを制作した。ロゴの制作には3週間の時間を要し、決定に至った。まずはじめに、メンバー全員がロゴ案を1案以上考案してロゴの発表会をおこない、それぞれの案についてレビューをおこなった。この段階ではそれぞれの案の良いところだけを伝える形式をとった。ここで受けたレ
「この発表会の後」
じゃなくても．
「発表会後」とかでもいいかも

2020-09-18 09:16 UTC, mrs1669 commented on chapter2.tex
> +実地調査は、プレ実施したのちに本実施した。プレ実施では、函館山で6月19日に実施した。本実施では、2.2.1節で述べた5つの地区で5つのグループに分かれて6月21日に実施した。ただし、COVID-19感染への対策として体調の管理やマスク着用必須、人混みや他人との接触・会話を避けるなどに注意することとした。五稜郭地区では、五稜郭公園、五稜郭タワー、五稜郭交差点地下横断歩道、千代台公園、JR五稜郭駅
```suggestion
実地調査は、プレ実施した後に本実施した。プレ実施では、函館山で6月19日に実施した。本実施では、2.2.1節で述べた5つの地区で5つのグループに分かれて6月21日に実施した。ただし、COVID-19感染への対策として体調の管理やマスク着用必須、人混みや他人との接触・会話を避けるなどに注意することとした。五稜郭地区では、五稜郭公園、五稜郭タワー、五稜郭交差点地下横断歩道、千代台公園、JR五稜郭駅、函館市中央図書館、六花亭で主に調査をおこなった。赤川・美原・昭和・富岡地区では、四季の杜公園、笹流ダム、四稜郭、住宅街で主に調査をおこなった。函館駅・西部地区では、函館駅周辺、金森赤レンガ倉庫、朝市、西部地区で主に調査をおこなった。七飯・北斗地区では、男爵ラウンジ、なないろ・ななえ、新函館北斗駅、大沼公園、山川牧場で主に調査をおこなった。空港・湯の川地区では、あいす118、函館空港、トラピスチヌ修道院、香雪園、植物園、函館公園、十字街で主に調査をおこなった。また、各グループでSlackにチャンネルを作成し、調査をおこないながら写真や文章で情報をリアルタイムで共有した。
```

2020-09-18 09:16 UTC, mrs1669 commented on chapter2.tex
> +実地調査は、プレ実施したのちに本実施した。プレ実施では、函館山で6月19日に実施した。本実施では、2.2.1節で述べた5つの地区で5つのグループに分かれて6月21日に実施した。ただし、COVID-19感染への対策として体調の管理やマスク着用必須、人混みや他人との接触・会話を避けるなどに注意することとした。五稜郭地区では、五稜郭公園、五稜郭タワー、五稜郭交差点地下横断歩道、千代台公園、JR五稜郭駅
というか，ここの説明全体的に日本語がおかしい気がする．

「プレ実施」，「本実施」というより
「プレ調査」，「本調査」のほうがしっくりくる

2020-09-18 09:27 UTC, yuhei-yama commented on chapter2.tex
> +本プロジェクトでは、プロジェクトの特徴やイメージを表現するため、加えて議論の練習と、メンバー全員の一体感を生むために、今年度のプロジェクトのロゴを制作した。ロゴの制作には3週間の時間を要し、決定に至った。まずはじめに、メンバー全員がロゴ案を1案以上考案してロゴの発表会をおこない、それぞれの案についてレビューをおこなった。この段階ではそれぞれの案の良いところだけを伝える形式をとった。ここで受けたレ
修正しました！　確認お願いします！

2020-09-18 09:28 UTC, yuhei-yama commented on chapter2.tex
> +実地調査は、プレ実施したのちに本実施した。プレ実施では、函館山で6月19日に実施した。本実施では、2.2.1節で述べた5つの地区で5つのグループに分かれて6月21日に実施した。ただし、COVID-19感染への対策として体調の管理やマスク着用必須、人混みや他人との接触・会話を避けるなどに注意することとした。五稜郭地区では、五稜郭公園、五稜郭タワー、五稜郭交差点地下横断歩道、千代台公園、JR五稜郭駅
修正しました！　確認お願いします！

2020-09-18 09:31 UTC, massu116 commented on chapter2.tex
> +本プロジェクトの提供サービス考案までのプロセスは、大きく4つに分かれる。1つ目は、フィールドワークである。実際に函館を見て回り、街にある課題を探した。2つ目はブレインストーミングとKJ法（以下BSKJ法）である。フィールドワークで感じたことや、これまでの自身の体験をもとに函館の街に存在する課題を割り出し、それらをグルーピングした。3つ目はオープン・スペース・テクノロジー（以下OST）である。OS
アイデアの解像度って言葉にあまり馴染みがないんだけど、アイデアを磨くとかじゃニュアンス違う感じ？？

2020-09-18 09:37 UTC, yuhei-yama commented on chapter2.tex
> +本プロジェクトの提供サービス考案までのプロセスは、大きく4つに分かれる。1つ目は、フィールドワークである。実際に函館を見て回り、街にある課題を探した。2つ目はブレインストーミングとKJ法（以下BSKJ法）である。フィールドワークで感じたことや、これまでの自身の体験をもとに函館の街に存在する課題を割り出し、それらをグルーピングした。3つ目はオープン・スペース・テクノロジー（以下OST）である。OS
アイデアを磨くはブラッシュアップになるから少しニュアンスが違うらしい

2020-09-18 09:38 UTC, mrs1669 requested changes
![後醍醐天皇のイラスト](https://2.bp.blogspot.com/-c_F7akCfzHM/VuKD-EBfCoI/AAAAAAAA4ww/MINV7FRn2BYOvB-f5Cx-yQYJm4F3rhVZA/s450/nigaoe_godaigo_tennou.png)

2020-09-18 09:38 UTC, mrs1669 commented on chapter2.tex
> +本プロジェクトではビーコンを使用した開発をおこなうために、ビーコンに関する知識を深める必要があると判断し、事前調査をおこなった。事前調査は「近接・位置即位」「GPSとの機能・特性比較」「各種センサとの連携」「LINE Beacon」「適用事例」の5つの項目についておこなった。各項目にメンバーを3名ずつ割り振って調査をおこない、調査した内容を各グループスライドにまとめ、共有した。この事前調査によっ
即位しちゃったかぁ～
![sokui](https://user-images.githubusercontent.com/40351476/93582880-0cbd2600-f9de-11ea-98f6-3526c2482eb2.jpg)
```suggestion
本プロジェクトではビーコンを使用した開発をおこなうために、ビーコンに関する知識を深める必要があると判断し、事前調査をおこなった。事前調査は「近接・位置測位」「GPSとの機能・特性比較」「各種センサとの連携」「LINE Beacon」「適用事例」の5つの項目についておこなった。各項目にメンバーを3名ずつ割り振って調査をおこない、調査した内容を各グループスライドにまとめ、共有した。この事前調査によって、ビーコンの特徴や機能など、様々な知識を会得することができた。またこの調査は、アイデアにビーコンらしさを取り入れる点で非常に役立っている。
```

2020-09-18 09:51 UTC, mrs1669 requested changes
![寿司ゆき:faint](https://d1zd1v0cxnbx2w.cloudfront.net/images/sets/sushiyuki/76.png)

2020-09-18 09:51 UTC, mrs1669 commented on chapter2.tex
> +本プロジェクトでは、プロジェクトの特徴やイメージを表現するため、加えて議論の練習と、メンバー全員の一体感を生むために、今年度のプロジェクトのロゴを制作した。ロゴの制作には3週間の時間を要し、決定に至った。まずはじめに、メンバー全員がロゴ案を1案以上考案してロゴの発表会をおこない、それぞれの案についてレビューをおこなった。この段階ではそれぞれの案の良いところだけを伝える形式をとった。ここで受けたレ
「メンバー、TA、先生を交えて」
61行目「学生と教員間」

先生と教員の表記ゆれ

2020-09-18 09:51 UTC, mrs1669 commented on chapter2.tex
> +KJ法ですべての班のアイデアのグルーピングをおこなった結果からブラッシュアップをおこなうにあたりアイデアの絞り込みをおこなった。メンバーは1～4点の計10点を持ち点として各々が興味のあるアイデアに投票をおこない、絞りこみをおこなった。その結果、中間発表の時点では「お店とビーコン」「観光」「隠れスポット」「施設とビーコン」の4つの項目に絞ることができた。その後、これらのアイデアに3～4人割り振って
「学生と教員間」
70行目「メンバー、TA、先生を交えて」

先生と教員の表記ゆれ

2020-09-18 10:00 UTC, massu116 commented on chapter2.tex
> +本プロジェクトの提供サービス考案までのプロセスは、大きく4つに分かれる。1つ目は、フィールドワークである。実際に函館を見て回り、街にある課題を探した。2つ目はブレインストーミングとKJ法（以下BSKJ法）である。フィールドワークで感じたことや、これまでの自身の体験をもとに函館の街に存在する課題を割り出し、それらをグルーピングした。3つ目はオープン・スペース・テクノロジー（以下OST）である。OS
アイデアのイメージを固めるとかは？

2020-09-18 10:04 UTC, mrs1669 commented
雄平の最新の治ってないよ

2020-09-18 10:05 UTC, mrs1669 commented
最新のfix chapter2 commit確認すると行が一行追加されてるだけみたい

2020-09-18 10:08 UTC, yuhei-yama commented
すまない！
今、送ったものは治っていると思う

2020-09-18 10:22 UTC, yuhei-yama commented on chapter2.tex
> +本プロジェクトの提供サービス考案までのプロセスは、大きく4つに分かれる。1つ目は、フィールドワークである。実際に函館を見て回り、街にある課題を探した。2つ目はブレインストーミングとKJ法（以下BSKJ法）である。フィールドワークで感じたことや、これまでの自身の体験をもとに函館の街に存在する課題を割り出し、それらをグルーピングした。3つ目はオープン・スペース・テクノロジー（以下OST）である。OS
アイデアを鮮明にしたで直してみた

2020-09-18 11:30 UTC, ogi-san commented on chapter2.tex
> +ハッカソンはハックとマラソンを掛け合わせた造語で、チームを作成し、短期間でサービスやシステム、アプリケーションを開発し、成果を競うイベントの一種である。私たちはこのハッカソンを2回のアイデア出しに用いた。以下ハッカソン方式と呼ぶ。1回目は、4人1グループを作成し、90分の時間制限を設けてアイデアを出しをおこなった。2回目は参加者が順番に出題し、5分の時間制限を設けてお題に沿ったアイデア出しをおこ
```suggestion
ハッカソンはハックとマラソンを掛け合わせた造語で、チームを作成し、短期間でサービスやシステム、アプリケーションを開発し、成果を競うイベントの一種である。私たちはこのハッカソンを2回のアイデア出しに用いた。以下ハッカソン方式と呼ぶ。1回目は、4人1グループを作成し、90分の時間制限を設けてアイデアを出しをおこなった。2回目は参加者が順番に出題し、5分の時間制限を設けてお題に沿ったアイデア出しをおこなった。この方式ではそれぞれがアイデアの絵を描いてメンバーにイメージを共有しながら進めていった。
```

2020-09-18 11:31 UTC, merged