Draft/chapter6
beaconFUN/mid-report2020 pull request #9
Opened 2020-09-17 12:41 UTC by kume-negitoro

本文の内容と誤字・脱字、表記揺れあたりの確認をお願いします。
また、こちらで気になっているのは以下の点です。

- 「リーダーを設けないチーム運営」のセクション名
- 「リーダーを設けないチーム運営」の、文の繋ぎが上手くない
- 「情報共有」の「そのため」から始まる文が長い

こちらもレビューをよろしくお願いします。

2020-09-17 12:52 UTC, D1438 commented
- ”情報をアウトプットする技術”の上から２行目「他メンバ」→「他メンバー」
 - ”サービス設計”の上から４行目「,」→「、」
 - ”Google Jamboard”か”GoogleJamboard”かどっちかの方がいい

2020-09-17 12:54 UTC, kume-negitoro commented
@D1438 ありがとう！修正します！

2020-09-17 13:14 UTC, santyoume commented on chapter6.tex
> +フィールドワークを行った場所は、函館山・西部地区・函館駅周辺・湯の川方面・五稜郭周辺・赤川・七飯町周辺の8ヶ所である。
２章でフィールドワークについて書いた時は「五稜郭」「赤川・美原・昭和・富岡」「函館駅・西部地区」「七飯・北斗」「空港・湯の川」の5地区っていってるんだよね…どっちかに統一した方がいいかな

2020-09-17 13:18 UTC, massu116 requested changes

2020-09-17 13:18 UTC, massu116 commented on chapter6.tex
> +この8ヶ所を回り、思ったことや気づいたことについてGoogle Jamboradを使用して、付箋に書き出し、似ている意見をまとめてラベルを付け、KJ法を用いて意見の関連を明らかにした。
```suggestion
この8ヶ所を回り、思ったことや気づいたことについてGoogle Jamboradを使用して、付箋に書き出し、似ている意見にまとめてラベルを付け、KJ法を用いて意見の関連を明らかにした。
```

2020-09-17 13:18 UTC, massu116 commented on chapter6.tex
> +その際、BSKJ法に加え、時間内にテーマに沿ったアイデアを考案するという手法(ハッカソン形式)を用いて、サービスのアイデアをより良いものにした（洗練させた）。
(本プロジェクトではハッカソン形式と呼ぶ)みたいな説明の方がわかりやすいかも？？

2020-09-17 13:18 UTC, massu116 commented on chapter6.tex
> +小規模なOSTを用いて、自身が興味のあるアイデアに対してさらに議論を深めていく方式をとることにより、より活発な議論を行うことができた。
```suggestion
小規模なOSTを用いて、自身が興味のあるアイデアに対してさらに議論を深めていく方式をとることにより、より活発な議論を行うこともできた。
```

2020-09-17 13:20 UTC, kumakou commented on chapter6.tex
> +フィールドワークを行った場所は、函館山・西部地区・函館駅周辺・湯の川方面・五稜郭周辺・赤川・七飯町周辺の8ヶ所である。
ちゃんとグループごとにどこ行ったのかわかるから、2章の人たちの書き方で統一しましょう！

2020-09-17 13:27 UTC, kume-negitoro commented on chapter6.tex
> +その際、BSKJ法に加え、時間内にテーマに沿ったアイデアを考案するという手法(ハッカソン形式)を用いて、サービスのアイデアをより良いものにした（洗練させた）。
@massu116 ありがとう！この章以前にハッカソン形式が登場するところがあれば、そっちの方に書いた方がいいかもしれん。

2020-09-17 13:27 UTC, mrs1669 commented on chapter6.tex
> +また、教員やTA、他のグループメンバーによるレビューにより，問題点を繰り返し修正した。
`レビューにより，問題点を`
コンマが残ってます
![ミサワ](https://livedoor.blogimg.jp/jigokuno_misawa/imgs/b/e/be6bbadc.gif)

2020-09-17 13:28 UTC, massu116 commented on chapter6.tex
> +その際、BSKJ法に加え、時間内にテーマに沿ったアイデアを考案するという手法(ハッカソン形式)を用いて、サービスのアイデアをより良いものにした（洗練させた）。
あー、これ以前にも出てきそうだね
ハッカソン形式自体が造語だからどこかで補足は入れておいて欲しいとは思う

2020-09-17 13:29 UTC, kume-negitoro commented on chapter6.tex
> +また、教員やTA、他のグループメンバーによるレビューにより，問題点を繰り返し修正した。
@mrs1669 修正します！ありがとう！

2020-09-17 13:30 UTC, Ryuku-Hisa requested changes

2020-09-17 13:30 UTC, Ryuku-Hisa commented on chapter6.tex
> +ロゴ製作では、メンバ各自がプロジェクトのイメージを考えロゴをデザインし、製作したロゴのイメージをオンライン発表を通して他メンバに伝えた。
「メンバ→メンバー」にということ表記に統一で（Slack見て遅れ）
なんか「イメージ」「デザイン」「制作」の3つの単語の使い方に統一性がない気がする
こんな感じにしてみたら？
```suggestion
ロゴ製作では、メンバー各自がプロジェクトのイメージを考えてロゴをデザインした。製作したロゴはオンライン上で発表し、他メンバに伝えた。
```

2020-09-17 13:30 UTC, Ryuku-Hisa commented on chapter6.tex
> +フィールドワークでは、函館市内8ヶ所にフィールドワークを行った。
```suggestion
フィールドワークでは、函館市内8ヶ所でフィールドワークを行った。
```

2020-09-17 13:30 UTC, Ryuku-Hisa commented on chapter6.tex
> +サービス考案では、フィールドワークのまとめや自身の経験からサービスのアイデアを考えた。
```suggestion
サービス考案では、フィールドワークのまとめや、自身の経験からサービスのアイデアを考えた。
```

2020-09-17 13:30 UTC, Ryuku-Hisa commented on chapter6.tex
> +その際、BSKJ法に加え、時間内にテーマに沿ったアイデアを考案するという手法(ハッカソン形式)を用いて、サービスのアイデアをより良いものにした（洗練させた）。
「サービスのアイデアをより良いものにした（洗練させた）」
なんか，この（）が最後にあるの気になるな．．．
単に，「アイデアを洗練した」でいいんじゃない？
あと，アイデアは洗練されるが，洗練しているのは私たちなので，
私たちがアイデアを洗練した➡アイデアを洗練した　[主語の省略]
ではないだろうか？
```suggestion
その際、BSKJ法に加え、時間内にテーマに沿ったアイデアを考案するという手法(ハッカソン形式)を用いて、サービスのアイデアを洗練した。
```

2020-09-17 13:30 UTC, Ryuku-Hisa commented on chapter6.tex
> +またSlackワークスペース内に、思いついたアイデアを誰でも自由に書き込めるチャンネルを作ることで、ユニークなアイデアを発見できる機会を増やすことができた。
```suggestion
また、Slackワークスペース内に、思いついたアイデアを誰でも自由に書き込めるチャンネルを作ることで、ユニークなアイデアを発見できる機会を増やすことができた。
```

2020-09-17 13:30 UTC, Ryuku-Hisa commented on chapter6.tex
> +聞き手に伝わるようにスライドとポスターの文章を添削し、聞き手がわかりにくいと感じた部分を修正することによって、アウトプットの技術を高めることができた。
断定はできないかな
```suggestion
聞き手に伝わるようにスライドとポスターの文章を添削し、聞き手がわかりにくいと感じるであろう部分を修正することによって、アウトプットの技術を高めることができた。
```

2020-09-17 13:30 UTC, Ryuku-Hisa commented on chapter6.tex
> +各週を担当するファシリテータはバックログを基に次週行うタスクを選択し、それに従ってプロジェクトの管理を行った。
```suggestion
各週を担当するファシリテータは、バックログをもとに次週行うタスクを選択し、それに従ってプロジェクトのスケジュール管理を行った。
```

2020-09-17 13:30 UTC, Ryuku-Hisa commented on chapter6.tex
> +特に今年度はコロナウイルス感染拡大を考慮し、Zoomを使用したオンラインでの活動が主となった。
```suggestion
とくに、今年度はコロナウイルスの感染拡大を考慮し、Zoomを使用したオンラインでの活動が主となった。
```

2020-09-17 13:37 UTC, kumakou commented on chapter6.tex
> +サービス考案では、フィールドワークのまとめや自身の経験からサービスのアイデアを考えた。
取り込みます！

2020-09-17 14:01 UTC, kume-negitoro commented on chapter6.tex
> +小規模なOSTを用いて、自身が興味のあるアイデアに対してさらに議論を深めていく方式をとることにより、より活発な議論を行うことができた。
@massu116 似た形式の文章が続くのは確かに気になるんだけど、「も」で繋げるのも少し違う気がするんだよね...

2020-09-17 14:26 UTC, naonom commented on chapter6.tex
> +コロナ禍というのを加味して、今回提案するサービスの「函館らしさ」「ビーコンである理由」「必要性」「新規性」「不変的な魅力」という点についてブレインストーミングやKJ法を用いて徹底的に議論した。
```suggestion
コロナ禍というのを加味して、今回提案するサービスの「サービスの函館らしさ」「ビーコンである理由」「サービスの必要性」「サービスの新規性」「サービスの不変的な魅力」という点についてブレインストーミングやKJ法を用いて徹底的に議論した。
```

2020-09-17 14:36 UTC, massu116 commented on chapter6.tex
> +小規模なOSTを用いて、自身が興味のあるアイデアに対してさらに議論を深めていく方式をとることにより、より活発な議論を行うことができた。
◯◯ができた。
◯◯ができた。
って書き方だと箇条書きみたいな感じに見えちゃうから、この書き方で行くなら、以上のことより〜みたいなまとめが欲しくなるかなー

2020-09-17 14:56 UTC, kumakou commented on chapter6.tex
> +これらを解決するためには、全員の同意を取るなどの意思決定作業を自動化することにより、より具体的な作業内容の話し合いに時間を使うべきであると考える。
みんなの意見がそろったらdをするとかのやつを自動化っていう表現にしたんだけど、いい感じの表現があったらおしえてほしいです…

2020-09-17 14:58 UTC, kumakou commented
ハッカソン形式からハッカソン手法に変更した。

2020-09-17 14:59 UTC, kumakou commented
「コロナ禍」を「COVID-19の影響で生活様式が変化したこと」に変更

2020-09-17 15:01 UTC, santyoume commented on chapter6.tex
> +とくに、今年度はコロナウイルスの感染拡大を考慮し、Zoomを使用したオンラインでの活動が主となった。
こうへいとかと話した時にコロナウイルス系はCOVID-19で統一しようって話になった
```suggestion
とくに、今年度はCOVID-19の感染拡大を考慮し、Zoomを使用したオンラインでの活動が主となった。
```

2020-09-17 15:04 UTC, Kohei-Oishi commented on chapter6.tex
> +とくに、今年度はコロナウイルスの感染拡大を考慮し、Zoomを使用したオンラインでの活動が主となった。
そやな
あんがと侍

2020-09-17 15:10 UTC, kumakou commented on chapter6.tex
> +これらを解決するためには、全員の同意を取るなどの意思決定作業を自動化することにより、より具体的な作業内容の話し合いに時間を使うべきであると考える。
あと、アンケートで意見をとるとか

2020-09-17 15:25 UTC, kume-negitoro commented on chapter6.tex
> +これらを解決するためには、全員の同意を取るなどの意思決定作業を自動化することにより、より具体的な作業内容の話し合いに時間を使うべきであると考える。
```suggestion
これらを解決するために、より具体的な作業内容の話し合いに時間を使うべきであると考える。
具体的な方針としては、話し合いに加えてアンケート機能などを使うことで、意思決定作業を効率化することが提案されている。
```

2020-09-17 15:59 UTC, kume-negitoro commented on chapter6.tex
> +小規模なOSTを用いて、自身が興味のあるアイデアに対してさらに議論を深めていく方式をとることにより、より活発な議論を行うことができた。
```suggestion
小規模なOSTを用いて、自身が興味のあるアイデアに対し、さらに議論を深めていく方式をとることにより、より活発な議論を行うことができた。
これらによって、多くのアイデアの中から、メンバーそれぞれの良いと思った部分を組み合わせ、ブラッシュアップを行うことができた。
```

2020-09-17 16:01 UTC, kumakou approved these changes

2020-09-17 16:02 UTC, Kohei-Oishi submitted a review, later dismissed

2020-09-17 16:04 UTC, massu116 requested changes

2020-09-17 16:04 UTC, massu116 commented on chapter6.tex
> +前期のプロジェクトを通して、どのようにしてサービスを設計するかを学ぶことができた。
```suggestion
前期のプロジェクト活動を通して、どのようにしてサービスを設計するかを学ぶことができた。
```

2020-09-17 16:06 UTC, massu116 commented on chapter6.tex
> +前期の活動では、Beacon FUNにおける初めての試みとして、チーム内でリーダーを決めず、進行役を週ごとの交代制にした。
Beacon FUN 4??

2020-09-17 16:11 UTC, massu116 requested changes

2020-09-17 16:11 UTC, massu116 commented on chapter6.tex
> +ファシリテータを中心に、タスクを全員が把握するために使用するバックログを作成した。
```suggestion
ファシリテータを中心に、タスクを全員が把握する必要があるため、バックログを作成した。
```

2020-09-17 16:14 UTC, kumakou commented on chapter6.tex
> +前期の活動では、Beacon FUNにおける初めての試みとして、チーム内でリーダーを決めず、進行役を週ごとの交代制にした。
```suggestion
前期の活動では、Beacon FUN 4における初めての試みとして、チーム内でリーダーを決めず、進行役を週ごとの交代制にした。
```

2020-09-17 16:15 UTC, kumakou submitted a review, later dismissed

2020-09-17 16:15 UTC, Kohei-Oishi approved these changes

2020-09-17 16:15 UTC, massu116 approved these changes
OKでぇす

2020-09-17 16:40 UTC, naonom submitted a review, later dismissed
d

2020-09-17 16:45 UTC, mrs1669 commented on chapter6.tex
> +そのため、情報共有の手段としてSlackやesa、Google Jamboardなどのオンラインツールを活用し、議事録やブレインストーミングの結果を文章に残すことで、網羅的に情報を共有できるような工夫を行った。
「行った」はひらがなの方がいいのでは

2020-09-17 16:45 UTC, mrs1669 commented on chapter6.tex
> +ロゴの作成やフィールドワークから得られたこと、アイデア出しでの意見交換、アイデア案の発表など、多くの場面で情報共有を行った。
「行った」はひらがなの方がいいのでは

2020-09-17 16:45 UTC, mrs1669 commented on chapter6.tex
> +各週を担当するファシリテータは、バックログをもとに次週行うタスクを選択し、それに従ってプロジェクトのスケジュール管理を行った。
「行った」はひらがなの方がいいのでは

2020-09-17 16:45 UTC, mrs1669 commented on chapter6.tex
> +前期では、ロゴ製作、フィールドワーク、サービス考案というアイデアをアウトプットする活動を行ってきた。
「行った」はひらがなの方がいいのでは

2020-09-17 16:45 UTC, mrs1669 commented on chapter6.tex
> +そのため、情報共有の手段としてSlackやesa、Google Jamboardなどのオンラインツールを活用し、議事録やブレインストーミングの結果を文章に残すことで、網羅的に情報を共有できるような工夫を行った。
網羅的という文面を残すなら、動画を残したという文章の後に書いた方がよさそう
網羅的という日本語には、物事の隅々まで理解するという意味合いを含むと思うので

2020-09-17 16:48 UTC, mrs1669 commented on chapter6.tex
> +バックログの作業もオンラインで行う必要があったため、Google Jamboardというホワイトボードツールを使用した。
タスクを全員が把握する必要があるため、
バックログの作業もオンラインで行う必要があったため、

時制が一致していない。
「バックログの作業もオンラインで行う必要があるため、」
でいいと思う

2020-09-17 16:56 UTC, Kohei-Oishi commented on chapter6.tex
> +そのため、情報共有の手段としてSlackやesa、Google Jamboardなどのオンラインツールを活用し、議事録やブレインストーミングの結果を文章に残すことで、網羅的に情報を共有できるような工夫を行った。
```suggestion
そのため、情報共有の手段としてSlackやesa、Google Jamboardなどのオンラインツールを活用し、議事録やブレインストーミングの結果を文章に残すことで、網羅的に情報を共有できるような工夫をおこなった。
```

2020-09-17 16:59 UTC, kume-negitoro commented on chapter6.tex
> +バックログの作業もオンラインで行う必要があったため、Google Jamboardというホワイトボードツールを使用した。
```suggestion
タスクを全員が把握する必要があるため、ファシリテータを中心にバックログを作成した。
バックログの作業もオンラインで行う必要があるため、Google Jamboardというホワイトボードツールを使用した。
```

2020-09-17 17:04 UTC, kume-negitoro commented on chapter6.tex
> +バックログの作業もオンラインで行う必要があったため、Google Jamboardというホワイトボードツールを使用した。
@mrs1669 ありがとう！

2020-09-17 17:11 UTC, kume-negitoro commented on chapter6.tex
> +そのため、情報共有の手段としてSlackやesa、Google Jamboardなどのオンラインツールを活用し、議事録やブレインストーミングの結果を文章に残すことで、網羅的に情報を共有できるような工夫を行った。
@mrs1669  順番修正しました！

2020-09-17 17:21 UTC, massu116 requested changes

2020-09-17 17:21 UTC, massu116 commented on chapter6.tex
> +フィールドワークでは、函館市内5ヶ所にフィールドワークを行った。
```suggestion
フィールドワークでは、函館市内5ヶ所でフィールドワークをおこなった。
```

2020-09-17 17:28 UTC, massu116 requested changes

2020-09-17 17:28 UTC, massu116 commented on chapter6.tex
> +フィールドワークを行った場所は、「五稜郭」「赤川・美原・昭和・富岡」「函館駅・西部地区」「七飯・北斗」「空港・湯の川」の5ヶ所である。
```suggestion
フィールドワークをおこなった場所は、「五稜郭」「赤川・美原・昭和・富岡」「函館駅・西部地区」「七飯・北斗」「空港・湯の川」の5ヶ所である。
```

2020-09-17 17:29 UTC, massu116 requested changes

2020-09-17 17:29 UTC, massu116 commented on chapter6.tex
> +これらによって、多くのアイデアの中から、メンバーそれぞれの良いと思った部分を組み合わせ、ブラッシュアップを行うことができた。
```suggestion
これらによって、多くのアイデアの中から、メンバーそれぞれの良いと思った部分を組み合わせ、ブラッシュアップをおこなうことができた。
```

2020-09-17 17:30 UTC, massu116 requested changes

2020-09-17 17:30 UTC, massu116 commented on chapter6.tex
> +最後にプロジェクトの中間発表では、スライドを用いたプロジェクト概要の説明を動画やポスターで行った。
```suggestion
最後にプロジェクトの中間発表では、スライドを用いたプロジェクト概要の説明を動画やポスターでおこなった。
```

2020-09-17 17:31 UTC, massu116 requested changes

2020-09-17 17:31 UTC, massu116 commented on chapter6.tex
> +さらに、全員の意見が一致するまで話し合いを行うことで、意見や意識を一つの方向に定めることができた。
```suggestion
さらに、全員の意見が一致するまで話し合いをおこなうことで、意見や意識を一つの方向に定めることができた。
```

2020-09-17 17:33 UTC, massu116 requested changes

2020-09-17 17:33 UTC, massu116 commented on chapter6.tex
> +この作業を行うことで、いつまでに何をして、これからは何をするべきなのかをプロジェクトのメンバー全員で共有することができた。
```suggestion
この作業をおこなうことで、いつまでに何をして、これからは何をするべきなのかをプロジェクトのメンバー全員で共有することができた。
```

2020-09-17 17:38 UTC, Kohei-Oishi submitted a review, later dismissed

2020-09-17 17:39 UTC, massu116 submitted a review, later dismissed
ええじゃないかええじゃないか

2020-09-17 17:41 UTC, naonom approved these changes
d

2020-09-17 17:48 UTC, mrs1669 commented on chapter6.tex
> +最後にプロジェクトの中間発表では、スライドを用いたプロジェクト概要の説明を動画やポスターで行った。
スライドを用いたプロジェクト概要の説明を動画ではしたけど、ポスターではしてない
この文面だと、ポスターでもスライドを用いたプロジェクト概要の説明したように読み取れる気がする

2020-09-17 17:57 UTC, kume-negitoro commented on chapter6.tex
> +最後にプロジェクトの中間発表では、スライドを用いたプロジェクト概要の説明を動画やポスターで行った。
@mrs1669 わかる。修正します。

2020-09-17 18:24 UTC, kume-negitoro commented on chapter6.tex
> +最後にプロジェクトの中間発表では、スライドを用いたプロジェクト概要の説明を動画やポスターで行った。
@mrs1669 最新コミットで誤解のないよう修正しました。確認お願いします。

2020-09-17 19:37 UTC, Kohei-Oishi approved these changes

2020-09-18 04:04 UTC, kumakou approved these changes

2020-09-18 05:16 UTC, Ryuku-Hisa approved these changes

2020-09-18 05:16 UTC, merged